package work.socialhub.planetlink.define.emoji

import kotlin.js.JsExport

@JsExport
@Suppress("unused")
enum class EmojiType(
    val emoji: String,
    val expr: String,
    val category: String,
    val level: Int?
) {
    // Auto Generated Code
    // see EmojiGenerator.java (Test)
    Hash("#️⃣", "hash", "Symbols", 13),
    KeycapStar("*️⃣", "keycap_star", "Symbols", 12),
    Zero("0️⃣", "zero", "Symbols", 10),
    One("1️⃣", "one", "Symbols", 8),
    Two("2️⃣", "two", "Symbols", 9),
    Three("3️⃣", "three", "Symbols", 9),
    Four("4️⃣", "four", "Symbols", 10),
    Five("5️⃣", "five", "Symbols", 10),
    Six("6️⃣", "six", "Symbols", 11),
    Seven("7️⃣", "seven", "Symbols", 11),
    Eight("8️⃣", "eight", "Symbols", 12),
    Nine("9️⃣", "nine", "Symbols", 11),
    Copyright("©️", "copyright", "Symbols", null),
    Registered("®️", "registered", "Symbols", null),
    Mahjong("🀄", "mahjong", "Activities", 11),
    BlackJoker("🃏", "black_joker", "Activities", 11),
    A("🅰️", "a", "Symbols", 9),
    B("🅱️", "b", "Symbols", 10),
    O2("🅾️", "o2", "Symbols", 11),
    Parking("🅿️", "parking", "Symbols", 11),
    Ab("🆎", "ab", "Symbols", 13),
    Cl("🆑", "cl", "Symbols", 14),
    Cool("🆒", "cool", "Symbols", 11),
    Free("🆓", "free", "Symbols", 12),
    Id("🆔", "id", "Symbols", 11),
    New("🆕", "new", "Symbols", 10),
    Ng("🆖", "ng", "Symbols", 13),
    Ok("🆗", "ok", "Symbols", 10),
    Sos("🆘", "sos", "Symbols", 9),
    Up("🆙", "up", "Symbols", 11),
    Vs("🆚", "vs", "Symbols", 11),
    FlagAc("🇦🇨", "flag-ac", "Flags", 15),
    FlagAd("🇦🇩", "flag-ad", "Flags", 14),
    FlagAe("🇦🇪", "flag-ae", "Flags", 10),
    FlagAf("🇦🇫", "flag-af", "Flags", 13),
    FlagAg("🇦🇬", "flag-ag", "Flags", 14),
    FlagAi("🇦🇮", "flag-ai", "Flags", 14),
    FlagAl("🇦🇱", "flag-al", "Flags", 13),
    FlagAm("🇦🇲", "flag-am", "Flags", 13),
    FlagAo("🇦🇴", "flag-ao", "Flags", 13),
    FlagAq("🇦🇶", "flag-aq", "Flags", 15),
    FlagAr("🇦🇷", "flag-ar", "Flags", 9),
    FlagAs("🇦🇸", "flag-as", "Flags", 14),
    FlagAt("🇦🇹", "flag-at", "Flags", 10),
    FlagAu("🇦🇺", "flag-au", "Flags", 10),
    FlagAw("🇦🇼", "flag-aw", "Flags", 14),
    FlagAx("🇦🇽", "flag-ax", "Flags", 14),
    FlagAz("🇦🇿", "flag-az", "Flags", 13),
    FlagBa("🇧🇦", "flag-ba", "Flags", 14),
    FlagBb("🇧🇧", "flag-bb", "Flags", 14),
    FlagBd("🇧🇩", "flag-bd", "Flags", 12),
    FlagBe("🇧🇪", "flag-be", "Flags", 11),
    FlagBf("🇧🇫", "flag-bf", "Flags", 15),
    FlagBg("🇧🇬", "flag-bg", "Flags", 13),
    FlagBh("🇧🇭", "flag-bh", "Flags", 13),
    FlagBi("🇧🇮", "flag-bi", "Flags", 14),
    FlagBj("🇧🇯", "flag-bj", "Flags", 13),
    FlagBl("🇧🇱", "flag-bl", "Flags", null),
    FlagBm("🇧🇲", "flag-bm", "Flags", 14),
    FlagBn("🇧🇳", "flag-bn", "Flags", 15),
    FlagBo("🇧🇴", "flag-bo", "Flags", 12),
    FlagBq("🇧🇶", "flag-bq", "Flags", null),
    FlagBr("🇧🇷", "flag-br", "Flags", 7),
    FlagBs("🇧🇸", "flag-bs", "Flags", 14),
    FlagBt("🇧🇹", "flag-bt", "Flags", 15),
    FlagBv("🇧🇻", "flag-bv", "Flags", 15),
    FlagBw("🇧🇼", "flag-bw", "Flags", 13),
    FlagBy("🇧🇾", "flag-by", "Flags", 14),
    FlagBz("🇧🇿", "flag-bz", "Flags", 15),
    FlagCa("🇨🇦", "flag-ca", "Flags", 9),
    FlagCc("🇨🇨", "flag-cc", "Flags", 16),
    FlagCd("🇨🇩", "flag-cd", "Flags", 13),
    FlagCf("🇨🇫", "flag-cf", "Flags", 16),
    FlagCg("🇨🇬", "flag-cg", "Flags", 14),
    FlagCh("🇨🇭", "flag-ch", "Flags", 11),
    FlagCi("🇨🇮", "flag-ci", "Flags", 11),
    FlagCk("🇨🇰", "flag-ck", "Flags", 16),
    FlagCl("🇨🇱", "flag-cl", "Flags", 9),
    FlagCm("🇨🇲", "flag-cm", "Flags", 12),
    Cn("🇨🇳", "cn", "Flags", 10),
    FlagCo("🇨🇴", "flag-co", "Flags", 9),
    FlagCp("🇨🇵", "flag-cp", "Flags", 12),
    FlagCr("🇨🇷", "flag-cr", "Flags", 12),
    FlagCu("🇨🇺", "flag-cu", "Flags", 11),
    FlagCv("🇨🇻", "flag-cv", "Flags", 15),
    FlagCw("🇨🇼", "flag-cw", "Flags", 15),
    FlagCx("🇨🇽", "flag-cx", "Flags", null),
    FlagCy("🇨🇾", "flag-cy", "Flags", 14),
    FlagCz("🇨🇿", "flag-cz", "Flags", 12),
    De("🇩🇪", "de", "Flags", 9),
    FlagDg("🇩🇬", "flag-dg", "Flags", null),
    FlagDj("🇩🇯", "flag-dj", "Flags", 15),
    FlagDk("🇩🇰", "flag-dk", "Flags", 11),
    FlagDm("🇩🇲", "flag-dm", "Flags", 15),
    FlagDo("🇩🇴", "flag-do", "Flags", 11),
    FlagDz("🇩🇿", "flag-dz", "Flags", 10),
    FlagEa("🇪🇦", "flag-ea", "Flags", 13),
    FlagEc("🇪🇨", "flag-ec", "Flags", 10),
    FlagEe("🇪🇪", "flag-ee", "Flags", 13),
    FlagEg("🇪🇬", "flag-eg", "Flags", 10),
    FlagEh("🇪🇭", "flag-eh", "Flags", 15),
    FlagEr("🇪🇷", "flag-er", "Flags", 15),
    Es("🇪🇸", "es", "Flags", 9),
    FlagEt("🇪🇹", "flag-et", "Flags", 14),
    FlagEu("🇪🇺", "flag-eu", "Flags", 12),
    FlagFi("🇫🇮", "flag-fi", "Flags", 12),
    FlagFj("🇫🇯", "flag-fj", "Flags", 14),
    FlagFk("🇫🇰", "flag-fk", "Flags", 16),
    FlagFm("🇫🇲", "flag-fm", "Flags", 16),
    FlagFo("🇫🇴", "flag-fo", "Flags", 15),
    Fr("🇫🇷", "fr", "Flags", 9),
    FlagGa("🇬🇦", "flag-ga", "Flags", 14),
    Gb("🇬🇧", "gb", "Flags", 9),
    FlagGd("🇬🇩", "flag-gd", "Flags", 15),
    FlagGe("🇬🇪", "flag-ge", "Flags", 13),
    FlagGf("🇬🇫", "flag-gf", "Flags", 15),
    FlagGg("🇬🇬", "flag-gg", "Flags", 15),
    FlagGh("🇬🇭", "flag-gh", "Flags", 11),
    FlagGi("🇬🇮", "flag-gi", "Flags", 16),
    FlagGl("🇬🇱", "flag-gl", "Flags", 16),
    FlagGm("🇬🇲", "flag-gm", "Flags", 14),
    FlagGn("🇬🇳", "flag-gn", "Flags", 13),
    FlagGp("🇬🇵", "flag-gp", "Flags", 16),
    FlagGq("🇬🇶", "flag-gq", "Flags", 16),
    FlagGr("🇬🇷", "flag-gr", "Flags", 11),
    FlagGs("🇬🇸", "flag-gs", "Flags", null),
    FlagGt("🇬🇹", "flag-gt", "Flags", 12),
    FlagGu("🇬🇺", "flag-gu", "Flags", 15),
    FlagGw("🇬🇼", "flag-gw", "Flags", 15),
    FlagGy("🇬🇾", "flag-gy", "Flags", 14),
    FlagHk("🇭🇰", "flag-hk", "Flags", 12),
    FlagHm("🇭🇲", "flag-hm", "Flags", 16),
    FlagHn("🇭🇳", "flag-hn", "Flags", 12),
    FlagHr("🇭🇷", "flag-hr", "Flags", 12),
    FlagHt("🇭🇹", "flag-ht", "Flags", 13),
    FlagHu("🇭🇺", "flag-hu", "Flags", 12),
    FlagIc("🇮🇨", "flag-ic", "Flags", 15),
    FlagId("🇮🇩", "flag-id", "Flags", 10),
    FlagIe("🇮🇪", "flag-ie", "Flags", 11),
    FlagIl("🇮🇱", "flag-il", "Flags", 11),
    FlagIm("🇮🇲", "flag-im", "Flags", 15),
    FlagIn("🇮🇳", "flag-in", "Flags", 8),
    FlagIo("🇮🇴", "flag-io", "Flags", 16),
    FlagIq("🇮🇶", "flag-iq", "Flags", 12),
    FlagIr("🇮🇷", "flag-ir", "Flags", 13),
    FlagIs("🇮🇸", "flag-is", "Flags", 13),
    It("🇮🇹", "it", "Flags", 8),
    FlagJe("🇯🇪", "flag-je", "Flags", 16),
    FlagJm("🇯🇲", "flag-jm", "Flags", 11),
    FlagJo("🇯🇴", "flag-jo", "Flags", 12),
    Jp("🇯🇵", "jp", "Flags", 9),
    FlagKe("🇰🇪", "flag-ke", "Flags", 13),
    FlagKg("🇰🇬", "flag-kg", "Flags", 15),
    FlagKh("🇰🇭", "flag-kh", "Flags", 14),
    FlagKi("🇰🇮", "flag-ki", "Flags", null),
    FlagKm("🇰🇲", "flag-km", "Flags", 15),
    FlagKn("🇰🇳", "flag-kn", "Flags", 16),
    FlagKp("🇰🇵", "flag-kp", "Flags", 15),
    Kr("🇰🇷", "kr", "Flags", 9),
    FlagKw("🇰🇼", "flag-kw", "Flags", 12),
    FlagKy("🇰🇾", "flag-ky", "Flags", 16),
    FlagKz("🇰🇿", "flag-kz", "Flags", 14),
    FlagLa("🇱🇦", "flag-la", "Flags", 15),
    FlagLb("🇱🇧", "flag-lb", "Flags", 12),
    FlagLc("🇱🇨", "flag-lc", "Flags", 16),
    FlagLi("🇱🇮", "flag-li", "Flags", 16),
    FlagLk("🇱🇰", "flag-lk", "Flags", 12),
    FlagLr("🇱🇷", "flag-lr", "Flags", 11),
    FlagLs("🇱🇸", "flag-ls", "Flags", 15),
    FlagLt("🇱🇹", "flag-lt", "Flags", 13),
    FlagLu("🇱🇺", "flag-lu", "Flags", 13),
    FlagLv("🇱🇻", "flag-lv", "Flags", 13),
    FlagLy("🇱🇾", "flag-ly", "Flags", 12),
    FlagMa("🇲🇦", "flag-ma", "Flags", 11),
    FlagMc("🇲🇨", "flag-mc", "Flags", 11),
    FlagMd("🇲🇩", "flag-md", "Flags", 15),
    FlagMe("🇲🇪", "flag-me", "Flags", 14),
    FlagMf("🇲🇫", "flag-mf", "Flags", 15),
    FlagMg("🇲🇬", "flag-mg", "Flags", 13),
    FlagMh("🇲🇭", "flag-mh", "Flags", 16),
    FlagMk("🇲🇰", "flag-mk", "Flags", 13),
    FlagMl("🇲🇱", "flag-ml", "Flags", 13),
    FlagMm("🇲🇲", "flag-mm", "Flags", 14),
    FlagMn("🇲🇳", "flag-mn", "Flags", 15),
    FlagMo("🇲🇴", "flag-mo", "Flags", 15),
    FlagMp("🇲🇵", "flag-mp", "Flags", null),
    FlagMq("🇲🇶", "flag-mq", "Flags", 16),
    FlagMr("🇲🇷", "flag-mr", "Flags", 14),
    FlagMs("🇲🇸", "flag-ms", "Flags", null),
    FlagMt("🇲🇹", "flag-mt", "Flags", 14),
    FlagMu("🇲🇺", "flag-mu", "Flags", 15),
    FlagMv("🇲🇻", "flag-mv", "Flags", 15),
    FlagMw("🇲🇼", "flag-mw", "Flags", 15),
    FlagMx("🇲🇽", "flag-mx", "Flags", 8),
    FlagMy("🇲🇾", "flag-my", "Flags", 12),
    FlagMz("🇲🇿", "flag-mz", "Flags", 15),
    FlagNa("🇳🇦", "flag-na", "Flags", 14),
    FlagNc("🇳🇨", "flag-nc", "Flags", null),
    FlagNe("🇳🇪", "flag-ne", "Flags", 14),
    FlagNf("🇳🇫", "flag-nf", "Flags", 16),
    FlagNg("🇳🇬", "flag-ng", "Flags", 11),
    FlagNi("🇳🇮", "flag-ni", "Flags", 11),
    FlagNl("🇳🇱", "flag-nl", "Flags", 11),
    FlagNo("🇳🇴", "flag-no", "Flags", 11),
    FlagNp("🇳🇵", "flag-np", "Flags", 13),
    FlagNr("🇳🇷", "flag-nr", "Flags", null),
    FlagNu("🇳🇺", "flag-nu", "Flags", null),
    FlagNz("🇳🇿", "flag-nz", "Flags", 12),
    FlagOm("🇴🇲", "flag-om", "Flags", 14),
    FlagPa("🇵🇦", "flag-pa", "Flags", 12),
    FlagPe("🇵🇪", "flag-pe", "Flags", 10),
    FlagPf("🇵🇫", "flag-pf", "Flags", 16),
    FlagPg("🇵🇬", "flag-pg", "Flags", 15),
    FlagPh("🇵🇭", "flag-ph", "Flags", 10),
    FlagPk("🇵🇰", "flag-pk", "Flags", 9),
    FlagPl("🇵🇱", "flag-pl", "Flags", 11),
    FlagPm("🇵🇲", "flag-pm", "Flags", null),
    FlagPn("🇵🇳", "flag-pn", "Flags", 16),
    FlagPr("🇵🇷", "flag-pr", "Flags", 11),
    FlagPs("🇵🇸", "flag-ps", "Flags", 12),
    FlagPt("🇵🇹", "flag-pt", "Flags", 10),
    FlagPw("🇵🇼", "flag-pw", "Flags", 16),
    FlagPy("🇵🇾", "flag-py", "Flags", 11),
    FlagQa("🇶🇦", "flag-qa", "Flags", 12),
    FlagRe("🇷🇪", "flag-re", "Flags", 16),
    FlagRo("🇷🇴", "flag-ro", "Flags", 12),
    FlagRs("🇷🇸", "flag-rs", "Flags", 13),
    Ru("🇷🇺", "ru", "Flags", 11),
    FlagRw("🇷🇼", "flag-rw", "Flags", 14),
    FlagSa("🇸🇦", "flag-sa", "Flags", 11),
    FlagSb("🇸🇧", "flag-sb", "Flags", 16),
    FlagSc("🇸🇨", "flag-sc", "Flags", 16),
    FlagSd("🇸🇩", "flag-sd", "Flags", 12),
    FlagSe("🇸🇪", "flag-se", "Flags", 11),
    FlagSg("🇸🇬", "flag-sg", "Flags", 12),
    FlagSh("🇸🇭", "flag-sh", "Flags", null),
    FlagSi("🇸🇮", "flag-si", "Flags", 14),
    FlagSj("🇸🇯", "flag-sj", "Flags", null),
    FlagSk("🇸🇰", "flag-sk", "Flags", 13),
    FlagSl("🇸🇱", "flag-sl", "Flags", 14),
    FlagSm("🇸🇲", "flag-sm", "Flags", 15),
    FlagSn("🇸🇳", "flag-sn", "Flags", 13),
    FlagSo("🇸🇴", "flag-so", "Flags", 14),
    FlagSr("🇸🇷", "flag-sr", "Flags", 15),
    FlagSs("🇸🇸", "flag-ss", "Flags", 15),
    FlagSt("🇸🇹", "flag-st", "Flags", 16),
    FlagSv("🇸🇻", "flag-sv", "Flags", 12),
    FlagSx("🇸🇽", "flag-sx", "Flags", 15),
    FlagSy("🇸🇾", "flag-sy", "Flags", 12),
    FlagSz("🇸🇿", "flag-sz", "Flags", 16),
    FlagTa("🇹🇦", "flag-ta", "Flags", null),
    FlagTc("🇹🇨", "flag-tc", "Flags", 15),
    FlagTd("🇹🇩", "flag-td", "Flags", 14),
    FlagTf("🇹🇫", "flag-tf", "Flags", null),
    FlagTg("🇹🇬", "flag-tg", "Flags", 15),
    FlagTh("🇹🇭", "flag-th", "Flags", 11),
    FlagTj("🇹🇯", "flag-tj", "Flags", 14),
    FlagTk("🇹🇰", "flag-tk", "Flags", 16),
    FlagTl("🇹🇱", "flag-tl", "Flags", 16),
    FlagTm("🇹🇲", "flag-tm", "Flags", 15),
    FlagTn("🇹🇳", "flag-tn", "Flags", 11),
    FlagTo("🇹🇴", "flag-to", "Flags", 15),
    FlagTr("🇹🇷", "flag-tr", "Flags", 8),
    FlagTt("🇹🇹", "flag-tt", "Flags", 13),
    FlagTv("🇹🇻", "flag-tv", "Flags", null),
    FlagTw("🇹🇼", "flag-tw", "Flags", 13),
    FlagTz("🇹🇿", "flag-tz", "Flags", 13),
    FlagUa("🇺🇦", "flag-ua", "Flags", 11),
    FlagUg("🇺🇬", "flag-ug", "Flags", 13),
    FlagUm("🇺🇲", "flag-um", "Flags", 10),
    FlagUn("🇺🇳", "flag-un", "Flags", 15),
    Us("🇺🇸", "us", "Flags", 7),
    FlagUy("🇺🇾", "flag-uy", "Flags", 10),
    FlagUz("🇺🇿", "flag-uz", "Flags", 14),
    FlagVa("🇻🇦", "flag-va", "Flags", 15),
    FlagVc("🇻🇨", "flag-vc", "Flags", 16),
    FlagVe("🇻🇪", "flag-ve", "Flags", 10),
    FlagVg("🇻🇬", "flag-vg", "Flags", 16),
    FlagVi("🇻🇮", "flag-vi", "Flags", 15),
    FlagVn("🇻🇳", "flag-vn", "Flags", 12),
    FlagVu("🇻🇺", "flag-vu", "Flags", 16),
    FlagWf("🇼🇫", "flag-wf", "Flags", null),
    FlagWs("🇼🇸", "flag-ws", "Flags", 15),
    FlagXk("🇽🇰", "flag-xk", "Flags", 14),
    FlagYe("🇾🇪", "flag-ye", "Flags", 11),
    FlagYt("🇾🇹", "flag-yt", "Flags", null),
    FlagZa("🇿🇦", "flag-za", "Flags", 11),
    FlagZm("🇿🇲", "flag-zm", "Flags", 14),
    FlagZw("🇿🇼", "flag-zw", "Flags", 13),
    Koko("🈁", "koko", "Symbols", 15),
    Sa("🈂️", "sa", "Symbols", 15),
    U7121("🈚", "u7121", "Symbols", 13),
    U6307("🈯", "u6307", "Symbols", 14),
    U7981("🈲", "u7981", "Symbols", 13),
    U7a7a("🈳", "u7a7a", "Symbols", 14),
    U5408("🈴", "u5408", "Symbols", 13),
    U6e80("🈵", "u6e80", "Symbols", 12),
    U6709("🈶", "u6709", "Symbols", 14),
    U6708("🈷️", "u6708", "Symbols", 15),
    U7533("🈸", "u7533", "Symbols", 15),
    U5272("🈹", "u5272", "Symbols", 13),
    U55b6("🈺", "u55b6", "Symbols", 15),
    IdeographAdvantage("🉐", "ideograph_advantage", "Symbols", 11),
    Accept("🉑", "accept", "Symbols", 13),
    Cyclone("🌀", "cyclone", "Travel & Places", 8),
    Foggy("🌁", "foggy", "Travel & Places", 13),
    ClosedUmbrella("🌂", "closed_umbrella", "Travel & Places", 11),
    NightWithStars("🌃", "night_with_stars", "Travel & Places", 9),
    SunriseOverMountains("🌄", "sunrise_over_mountains", "Travel & Places", 10),
    Sunrise("🌅", "sunrise", "Travel & Places", 10),
    CitySunset("🌆", "city_sunset", "Travel & Places", 11),
    CitySunrise("🌇", "city_sunrise", "Travel & Places", 11),
    Rainbow("🌈", "rainbow", "Travel & Places", 5),
    BridgeAtNight("🌉", "bridge_at_night", "Travel & Places", 12),
    Ocean("🌊", "ocean", "Travel & Places", 7),
    Volcano("🌋", "volcano", "Travel & Places", 10),
    MilkyWay("🌌", "milky_way", "Travel & Places", 9),
    EarthAfrica("🌍", "earth_africa", "Travel & Places", 8),
    EarthAmericas("🌎", "earth_americas", "Travel & Places", 8),
    EarthAsia("🌏", "earth_asia", "Travel & Places", 9),
    GlobeWithMeridians("🌐", "globe_with_meridians", "Travel & Places", 9),
    NewMoon("🌑", "new_moon", "Travel & Places", 10),
    WaxingCrescentMoon("🌒", "waxing_crescent_moon", "Travel & Places", 11),
    FirstQuarterMoon("🌓", "first_quarter_moon", "Travel & Places", 12),
    Moon("🌔", "moon", "Travel & Places", 12),
    FullMoon("🌕", "full_moon", "Travel & Places", 10),
    WaningGibbousMoon("🌖", "waning_gibbous_moon", "Travel & Places", 12),
    LastQuarterMoon("🌗", "last_quarter_moon", "Travel & Places", 12),
    WaningCrescentMoon("🌘", "waning_crescent_moon", "Travel & Places", 12),
    CrescentMoon("🌙", "crescent_moon", "Travel & Places", 7),
    NewMoonWithFace("🌚", "new_moon_with_face", "Travel & Places", 7),
    FirstQuarterMoonWithFace("🌛", "first_quarter_moon_with_face", "Travel & Places", 9),
    LastQuarterMoonWithFace("🌜", "last_quarter_moon_with_face", "Travel & Places", 10),
    FullMoonWithFace("🌝", "full_moon_with_face", "Travel & Places", 8),
    SunWithFace("🌞", "sun_with_face", "Travel & Places", 6),
    Star2("🌟", "star2", "Travel & Places", 5),
    Stars("🌠", "stars", "Travel & Places", 8),
    Thermometer("🌡️", "thermometer", "Travel & Places", 11),
    MostlySunny("🌤️", "mostly_sunny", "Travel & Places", 10),
    BarelySunny("🌥️", "barely_sunny", "Travel & Places", 11),
    PartlySunnyRain("🌦️", "partly_sunny_rain", "Travel & Places", 11),
    RainCloud("🌧️", "rain_cloud", "Travel & Places", 8),
    SnowCloud("🌨️", "snow_cloud", "Travel & Places", 10),
    Lightning("🌩️", "lightning", "Travel & Places", 11),
    Tornado("🌪️", "tornado", "Travel & Places", 9),
    Fog("🌫️", "fog", "Travel & Places", 11),
    WindBlowingFace("🌬️", "wind_blowing_face", "Travel & Places", 10),
    Hotdog("🌭", "hotdog", "Food & Drink", 11),
    Taco("🌮", "taco", "Food & Drink", 10),
    Burrito("🌯", "burrito", "Food & Drink", 12),
    Chestnut("🌰", "chestnut", "Food & Drink", 10),
    Seedling("🌱", "seedling", "Animals & Nature", 7),
    EvergreenTree("🌲", "evergreen_tree", "Animals & Nature", 9),
    DeciduousTree("🌳", "deciduous_tree", "Animals & Nature", 8),
    PalmTree("🌴", "palm_tree", "Animals & Nature", 7),
    Cactus("🌵", "cactus", "Animals & Nature", 8),
    HotPepper("🌶️", "hot_pepper", "Food & Drink", 8),
    Tulip("🌷", "tulip", "Animals & Nature", 5),
    CherryBlossom("🌸", "cherry_blossom", "Animals & Nature", 4),
    Rose("🌹", "rose", "Animals & Nature", 4),
    Hibiscus("🌺", "hibiscus", "Animals & Nature", 6),
    Sunflower("🌻", "sunflower", "Animals & Nature", 6),
    Blossom("🌼", "blossom", "Animals & Nature", 6),
    Corn("🌽", "corn", "Food & Drink", 9),
    EarOfRice("🌾", "ear_of_rice", "Animals & Nature", 8),
    Herb("🌿", "herb", "Animals & Nature", 6),
    FourLeafClover("🍀", "four_leaf_clover", "Animals & Nature", 5),
    MapleLeaf("🍁", "maple_leaf", "Animals & Nature", 8),
    FallenLeaf("🍂", "fallen_leaf", "Animals & Nature", 8),
    Leaves("🍃", "leaves", "Animals & Nature", 6),
    Mushroom("🍄", "mushroom", "Food & Drink", 8),
    Tomato("🍅", "tomato", "Food & Drink", 8),
    Eggplant("🍆", "eggplant", "Food & Drink", 8),
    Grapes("🍇", "grapes", "Food & Drink", 9),
    Melon("🍈", "melon", "Food & Drink", 9),
    Watermelon("🍉", "watermelon", "Food & Drink", 8),
    Tangerine("🍊", "tangerine", "Food & Drink", 7),
    Lemon("🍋", "lemon", "Food & Drink", 8),
    Banana("🍌", "banana", "Food & Drink", 8),
    Pineapple("🍍", "pineapple", "Food & Drink", 9),
    Apple("🍎", "apple", "Food & Drink", 7),
    GreenApple("🍏", "green_apple", "Food & Drink", 9),
    Pear("🍐", "pear", "Food & Drink", 10),
    Peach("🍑", "peach", "Food & Drink", 7),
    Cherries("🍒", "cherries", "Food & Drink", 7),
    Strawberry("🍓", "strawberry", "Food & Drink", 6),
    Hamburger("🍔", "hamburger", "Food & Drink", 9),
    Pizza("🍕", "pizza", "Food & Drink", 8),
    MeatOnBone("🍖", "meat_on_bone", "Food & Drink", 9),
    PoultryLeg("🍗", "poultry_leg", "Food & Drink", 9),
    RiceCracker("🍘", "rice_cracker", "Food & Drink", 12),
    RiceBall("🍙", "rice_ball", "Food & Drink", 11),
    Rice("🍚", "rice", "Food & Drink", 9),
    Curry("🍛", "curry", "Food & Drink", 9),
    Ramen("🍜", "ramen", "Food & Drink", 8),
    Spaghetti("🍝", "spaghetti", "Food & Drink", 10),
    Bread("🍞", "bread", "Food & Drink", 9),
    Fries("🍟", "fries", "Food & Drink", 9),
    SweetPotato("🍠", "sweet_potato", "Food & Drink", 10),
    Dango("🍡", "dango", "Food & Drink", 9),
    Oden("🍢", "oden", "Food & Drink", 11),
    Sushi("🍣", "sushi", "Food & Drink", 9),
    FriedShrimp("🍤", "fried_shrimp", "Food & Drink", 9),
    FishCake("🍥", "fish_cake", "Food & Drink", 10),
    Icecream("🍦", "icecream", "Food & Drink", 8),
    ShavedIce("🍧", "shaved_ice", "Food & Drink", 10),
    IceCream("🍨", "ice_cream", "Food & Drink", 9),
    Doughnut("🍩", "doughnut", "Food & Drink", 9),
    Cookie("🍪", "cookie", "Food & Drink", 9),
    ChocolateBar("🍫", "chocolate_bar", "Food & Drink", 8),
    Candy("🍬", "candy", "Food & Drink", 8),
    Lollipop("🍭", "lollipop", "Food & Drink", 8),
    Custard("🍮", "custard", "Food & Drink", 9),
    HoneyPot("🍯", "honey_pot", "Food & Drink", 9),
    Cake("🍰", "cake", "Food & Drink", 8),
    Bento("🍱", "bento", "Food & Drink", 10),
    Stew("🍲", "stew", "Food & Drink", 11),
    FriedEgg("🍳", "fried_egg", "Food & Drink", 10),
    ForkAndKnife("🍴", "fork_and_knife", "Food & Drink", 9),
    Tea("🍵", "tea", "Food & Drink", 9),
    Sake("🍶", "sake", "Food & Drink", 10),
    WineGlass("🍷", "wine_glass", "Food & Drink", 8),
    Cocktail("🍸", "cocktail", "Food & Drink", 9),
    TropicalDrink("🍹", "tropical_drink", "Food & Drink", 9),
    Beer("🍺", "beer", "Food & Drink", 7),
    Beers("🍻", "beers", "Food & Drink", 6),
    BabyBottle("🍼", "baby_bottle", "Food & Drink", 8),
    KnifeForkPlate("🍽️", "knife_fork_plate", "Food & Drink", 9),
    Champagne("🍾", "champagne", "Food & Drink", 8),
    Popcorn("🍿", "popcorn", "Food & Drink", 9),
    Ribbon("🎀", "ribbon", "Activities", 7),
    Gift("🎁", "gift", "Activities", 6),
    Birthday("🎂", "birthday", "Food & Drink", 6),
    JackOLantern("🎃", "jack_o_lantern", "Activities", 10),
    ChristmasTree("🎄", "christmas_tree", "Activities", 11),
    Santa("🎅", "santa", "People & Body", 11),
    Fireworks("🎆", "fireworks", "Activities", 9),
    Sparkler("🎇", "sparkler", "Activities", 9),
    Balloon("🎈", "balloon", "Activities", 6),
    Tada("🎉", "tada", "Activities", 4),
    ConfettiBall("🎊", "confetti_ball", "Activities", 6),
    TanabataTree("🎋", "tanabata_tree", "Activities", 10),
    CrossedFlags("🎌", "crossed_flags", "Flags", 10),
    Bamboo("🎍", "bamboo", "Activities", 12),
    Dolls("🎎", "dolls", "Activities", 11),
    Flags("🎏", "flags", "Activities", 10),
    WindChime("🎐", "wind_chime", "Activities", 11),
    RiceScene("🎑", "rice_scene", "Activities", 12),
    SchoolSatchel("🎒", "school_satchel", "Objects", 11),
    MortarBoard("🎓", "mortar_board", "Objects", 9),
    Medal("🎖️", "medal", "Activities", 11),
    ReminderRibbon("🎗️", "reminder_ribbon", "Activities", 9),
    StudioMicrophone("🎙️", "studio_microphone", "Objects", 9),
    LevelSlider("🎚️", "level_slider", "Objects", 12),
    ControlKnobs("🎛️", "control_knobs", "Objects", 12),
    FilmFrames("🎞️", "film_frames", "Objects", 11),
    AdmissionTickets("🎟️", "admission_tickets", "Activities", 10),
    CarouselHorse("🎠", "carousel_horse", "Travel & Places", 11),
    FerrisWheel("🎡", "ferris_wheel", "Travel & Places", 11),
    RollerCoaster("🎢", "roller_coaster", "Travel & Places", 11),
    FishingPoleAndFish("🎣", "fishing_pole_and_fish", "Activities", 10),
    Microphone("🎤", "microphone", "Objects", 7),
    MovieCamera("🎥", "movie_camera", "Objects", 8),
    Cinema("🎦", "cinema", "Symbols", 13),
    Headphones("🎧", "headphones", "Objects", 8),
    Art("🎨", "art", "Activities", 9),
    Tophat("🎩", "tophat", "Objects", 9),
    CircusTent("🎪", "circus_tent", "Travel & Places", 11),
    Ticket("🎫", "ticket", "Activities", 10),
    Clapper("🎬", "clapper", "Objects", 9),
    PerformingArts("🎭", "performing_arts", "Activities", 10),
    VideoGame("🎮", "video_game", "Activities", 9),
    Dart("🎯", "dart", "Activities", 8),
    SlotMachine("🎰", "slot_machine", "Activities", 11),
    Emoji8ball("🎱", "8ball", "Activities", 10),
    GameDie("🎲", "game_die", "Activities", 10),
    Bowling("🎳", "bowling", "Activities", 12),
    FlowerPlayingCards("🎴", "flower_playing_cards", "Activities", 13),
    MusicalNote("🎵", "musical_note", "Objects", 6),
    Notes("🎶", "notes", "Objects", 4),
    Saxophone("🎷", "saxophone", "Objects", 10),
    Guitar("🎸", "guitar", "Objects", 8),
    MusicalKeyboard("🎹", "musical_keyboard", "Objects", 9),
    Trumpet("🎺", "trumpet", "Objects", 10),
    Violin("🎻", "violin", "Objects", 9),
    MusicalScore("🎼", "musical_score", "Objects", 7),
    RunningShirtWithSash("🎽", "running_shirt_with_sash", "Activities", 12),
    Tennis("🎾", "tennis", "Activities", 10),
    Ski("🎿", "ski", "Activities", 14),
    Basketball("🏀", "basketball", "Activities", 8),
    CheckeredFlag("🏁", "checkered_flag", "Flags", 8),
    Snowboarder("🏂", "snowboarder", "People & Body", 12),
    WomanRunning("🏃‍♀️", "woman-running", "People & Body", null),
    ManRunning("🏃‍♂️", "man-running", "People & Body", null),
    Runner("🏃", "runner", "People & Body", 6),
    WomanSurfing("🏄‍♀️", "woman-surfing", "People & Body", null),
    ManSurfing("🏄‍♂️", "man-surfing", "People & Body", null),
    Surfer("🏄", "surfer", "People & Body", 10),
    SportsMedal("🏅", "sports_medal", "Activities", 10),
    Trophy("🏆", "trophy", "Activities", 6),
    HorseRacing("🏇", "horse_racing", "People & Body", 10),
    Football("🏈", "football", "Activities", 10),
    RugbyFootball("🏉", "rugby_football", "Activities", 11),
    WomanSwimming("🏊‍♀️", "woman-swimming", "People & Body", null),
    ManSwimming("🏊‍♂️", "man-swimming", "People & Body", null),
    Swimmer("🏊", "swimmer", "People & Body", 9),
    WomanLiftingWeights("🏋️‍♀️", "woman-lifting-weights", "People & Body", null),
    ManLiftingWeights("🏋️‍♂️", "man-lifting-weights", "People & Body", null),
    WeightLifter("🏋️", "weight_lifter", "People & Body", 10),
    WomanGolfing("🏌️‍♀️", "woman-golfing", "People & Body", null),
    ManGolfing("🏌️‍♂️", "man-golfing", "People & Body", null),
    Golfer("🏌️", "golfer", "People & Body", 10),
    RacingMotorcycle("🏍️", "racing_motorcycle", "Travel & Places", 10),
    RacingCar("🏎️", "racing_car", "Travel & Places", 11),
    CricketBatAndBall("🏏", "cricket_bat_and_ball", "Activities", 10),
    Volleyball("🏐", "volleyball", "Activities", 10),
    FieldHockeyStickAndBall("🏑", "field_hockey_stick_and_ball", "Activities", 12),
    IceHockeyStickAndPuck("🏒", "ice_hockey_stick_and_puck", "Activities", 11),
    TableTennisPaddleAndBall("🏓", "table_tennis_paddle_and_ball", "Activities", 12),
    SnowCappedMountain("🏔️", "snow_capped_mountain", "Travel & Places", 11),
    Camping("🏕️", "camping", "Travel & Places", 11),
    BeachWithUmbrella("🏖️", "beach_with_umbrella", "Travel & Places", 9),
    BuildingConstruction("🏗️", "building_construction", "Travel & Places", 12),
    HouseBuildings("🏘️", "house_buildings", "Travel & Places", 12),
    Cityscape("🏙️", "cityscape", "Travel & Places", 12),
    DerelictHouseBuilding("🏚️", "derelict_house_building", "Travel & Places", 12),
    ClassicalBuilding("🏛️", "classical_building", "Travel & Places", 12),
    Desert("🏜️", "desert", "Travel & Places", 12),
    DesertIsland("🏝️", "desert_island", "Travel & Places", 10),
    NationalPark("🏞️", "national_park", "Travel & Places", 12),
    Stadium("🏟️", "stadium", "Travel & Places", 11),
    House("🏠", "house", "Travel & Places", 9),
    HouseWithGarden("🏡", "house_with_garden", "Travel & Places", 9),
    Office("🏢", "office", "Travel & Places", 11),
    PostOffice("🏣", "post_office", "Travel & Places", 12),
    EuropeanPostOffice("🏤", "european_post_office", "Travel & Places", 13),
    Hospital("🏥", "hospital", "Travel & Places", 10),
    Bank("🏦", "bank", "Travel & Places", 12),
    Atm("🏧", "atm", "Symbols", 12),
    Hotel("🏨", "hotel", "Travel & Places", 11),
    LoveHotel("🏩", "love_hotel", "Travel & Places", 10),
    ConvenienceStore("🏪", "convenience_store", "Travel & Places", 12),
    School("🏫", "school", "Travel & Places", 11),
    DepartmentStore("🏬", "department_store", "Travel & Places", 13),
    Factory("🏭", "factory", "Travel & Places", 13),
    IzakayaLantern("🏮", "izakaya_lantern", "Objects", 11),
    JapaneseCastle("🏯", "japanese_castle", "Travel & Places", 12),
    EuropeanCastle("🏰", "european_castle", "Travel & Places", 10),
    RainbowFlag("🏳️‍🌈", "rainbow-flag", "Flags", 9),
    WavingWhiteFlag("🏳️", "waving_white_flag", "Flags", 11),
    PirateFlag("🏴‍☠️", "pirate_flag", "Flags", null),
    FlagEngland("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "flag-england", "Flags", 12),
    FlagScotland("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "flag-scotland", "Flags", 12),
    FlagWales("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "flag-wales", "Flags", 13),
    WavingBlackFlag("🏴", "waving_black_flag", "Flags", 11),
    Rosette("🏵️", "rosette", "Animals & Nature", 10),
    Label("🏷️", "label", "Objects", 11),
    BadmintonRacquetAndShuttlecock("🏸", "badminton_racquet_and_shuttlecock", "Activities", 12),
    BowAndArrow("🏹", "bow_and_arrow", "Objects", 10),
    Amphora("🏺", "amphora", "Food & Drink", 13),
    SkinTone2("🏻", "skin-tone-2", "Skin Tones", null),
    SkinTone3("🏼", "skin-tone-3", "Skin Tones", null),
    SkinTone4("🏽", "skin-tone-4", "Skin Tones", null),
    SkinTone5("🏾", "skin-tone-5", "Skin Tones", null),
    SkinTone6("🏿", "skin-tone-6", "Skin Tones", null),
    Rat("🐀", "rat", "Animals & Nature", 10),
    Mouse2("🐁", "mouse2", "Animals & Nature", 11),
    Ox("🐂", "ox", "Animals & Nature", 10),
    WaterBuffalo("🐃", "water_buffalo", "Animals & Nature", 11),
    Cow2("🐄", "cow2", "Animals & Nature", 10),
    Tiger2("🐅", "tiger2", "Animals & Nature", 10),
    Leopard("🐆", "leopard", "Animals & Nature", 11),
    Rabbit2("🐇", "rabbit2", "Animals & Nature", 10),
    Cat2("🐈", "cat2", "Animals & Nature", 8),
    Dragon("🐉", "dragon", "Animals & Nature", 10),
    Crocodile("🐊", "crocodile", "Animals & Nature", 10),
    Whale2("🐋", "whale2", "Animals & Nature", 10),
    Snail("🐌", "snail", "Animals & Nature", 10),
    Snake("🐍", "snake", "Animals & Nature", 9),
    Racehorse("🐎", "racehorse", "Animals & Nature", 9),
    Ram("🐏", "ram", "Animals & Nature", 11),
    Goat("🐐", "goat", "Animals & Nature", 9),
    Sheep("🐑", "sheep", "Animals & Nature", 10),
    Monkey("🐒", "monkey", "Animals & Nature", 9),
    Rooster("🐓", "rooster", "Animals & Nature", 9),
    Chicken("🐔", "chicken", "Animals & Nature", 9),
    ServiceDog("🐕‍🦺", "service_dog", "Animals & Nature", null),
    Dog2("🐕", "dog2", "Animals & Nature", 8),
    Pig2("🐖", "pig2", "Animals & Nature", 9),
    Boar("🐗", "boar", "Animals & Nature", 11),
    Elephant("🐘", "elephant", "Animals & Nature", 10),
    Octopus("🐙", "octopus", "Animals & Nature", 9),
    Shell("🐚", "shell", "Animals & Nature", 10),
    Bug("🐛", "bug", "Animals & Nature", 10),
    Ant("🐜", "ant", "Animals & Nature", 9),
    Bee("🐝", "bee", "Animals & Nature", 8),
    Beetle("🐞", "beetle", "Animals & Nature", 9),
    Fish("🐟", "fish", "Animals & Nature", 8),
    TropicalFish("🐠", "tropical_fish", "Animals & Nature", 9),
    Blowfish("🐡", "blowfish", "Animals & Nature", 11),
    Turtle("🐢", "turtle", "Animals & Nature", 9),
    HatchingChick("🐣", "hatching_chick", "Animals & Nature", 9),
    BabyChick("🐤", "baby_chick", "Animals & Nature", 10),
    HatchedChick("🐥", "hatched_chick", "Animals & Nature", 8),
    Bird("🐦", "bird", "Animals & Nature", 9),
    Penguin("🐧", "penguin", "Animals & Nature", 10),
    Koala("🐨", "koala", "Animals & Nature", 11),
    Poodle("🐩", "poodle", "Animals & Nature", 10),
    DromedaryCamel("🐪", "dromedary_camel", "Animals & Nature", 11),
    Camel("🐫", "camel", "Animals & Nature", 12),
    Dolphin("🐬", "dolphin", "Animals & Nature", 9),
    Mouse("🐭", "mouse", "Animals & Nature", 10),
    Cow("🐮", "cow", "Animals & Nature", 10),
    Tiger("🐯", "tiger", "Animals & Nature", 9),
    Rabbit("🐰", "rabbit", "Animals & Nature", 8),
    Cat("🐱", "cat", "Animals & Nature", 8),
    DragonFace("🐲", "dragon_face", "Animals & Nature", 11),
    Whale("🐳", "whale", "Animals & Nature", 9),
    Horse("🐴", "horse", "Animals & Nature", 9),
    MonkeyFace("🐵", "monkey_face", "Animals & Nature", 10),
    Dog("🐶", "dog", "Animals & Nature", 6),
    Pig("🐷", "pig", "Animals & Nature", 7),
    Frog("🐸", "frog", "Animals & Nature", 7),
    Hamster("🐹", "hamster", "Animals & Nature", 11),
    Wolf("🐺", "wolf", "Animals & Nature", 9),
    Bear("🐻", "bear", "Animals & Nature", 8),
    PandaFace("🐼", "panda_face", "Animals & Nature", 8),
    PigNose("🐽", "pig_nose", "Animals & Nature", 9),
    Feet("🐾", "feet", "Animals & Nature", 7),
    Chipmunk("🐿️", "chipmunk", "Animals & Nature", 11),
    Eyes("👀", "eyes", "People & Body", 5),
    EyeInSpeechBubble("👁️‍🗨️", "eye-in-speech-bubble", "Smileys & Emotion", 12),
    Eye("👁️", "eye", "People & Body", 8),
    Ear("👂", "ear", "People & Body", 9),
    Nose("👃", "nose", "People & Body", 10),
    Lips("👄", "lips", "People & Body", 8),
    Tongue("👅", "tongue", "People & Body", 7),
    PointUp2("👆", "point_up_2", "People & Body", 7),
    PointDown("👇", "point_down", "People & Body", 4),
    PointLeft("👈", "point_left", "People & Body", 6),
    PointRight("👉", "point_right", "People & Body", 5),
    Facepunch("👊", "facepunch", "People & Body", 5),
    Wave("👋", "wave", "People & Body", 6),
    OkHand("👌", "ok_hand", "People & Body", 3),
    EmojiPlus1("👍", "+1", "People & Body", 3),
    EmojiMinus1("👎", "-1", "People & Body", 7),
    Clap("👏", "clap", "People & Body", 3),
    OpenHands("👐", "open_hands", "People & Body", 7),
    Crown("👑", "crown", "Objects", 6),
    WomansHat("👒", "womans_hat", "Objects", 11),
    Eyeglasses("👓", "eyeglasses", "Objects", 10),
    Necktie("👔", "necktie", "Objects", 10),
    Shirt("👕", "shirt", "Objects", 10),
    Jeans("👖", "jeans", "Objects", 11),
    Dress("👗", "dress", "Objects", 10),
    Kimono("👘", "kimono", "Objects", 11),
    Bikini("👙", "bikini", "Objects", 9),
    WomansClothes("👚", "womans_clothes", "Objects", 11),
    Purse("👛", "purse", "Objects", 11),
    Handbag("👜", "handbag", "Objects", 12),
    Pouch("👝", "pouch", "Objects", 13),
    MansShoe("👞", "mans_shoe", "Objects", 11),
    AthleticShoe("👟", "athletic_shoe", "Objects", 10),
    HighHeel("👠", "high_heel", "Objects", 9),
    Sandal("👡", "sandal", "Objects", 11),
    Boot("👢", "boot", "Objects", 11),
    Footprints("👣", "footprints", "People & Body", 9),
    BustInSilhouette("👤", "bust_in_silhouette", "People & Body", 9),
    BustsInSilhouette("👥", "busts_in_silhouette", "People & Body", 10),
    Boy("👦", "boy", "People & Body", 9),
    Girl("👧", "girl", "People & Body", 8),
    MaleFarmer("👨‍🌾", "male-farmer", "People & Body", 12),
    MaleCook("👨‍🍳", "male-cook", "People & Body", 11),
    MaleStudent("👨‍🎓", "male-student", "People & Body", 11),
    MaleSinger("👨‍🎤", "male-singer", "People & Body", 13),
    MaleArtist("👨‍🎨", "male-artist", "People & Body", 13),
    MaleTeacher("👨‍🏫", "male-teacher", "People & Body", 12),
    MaleFactoryWorker("👨‍🏭", "male-factory-worker", "People & Body", 14),
    ManBoyBoy("👨‍👦‍👦", "man-boy-boy", "People & Body", 15),
    ManBoy("👨‍👦", "man-boy", "People & Body", 14),
    ManGirlBoy("👨‍👧‍👦", "man-girl-boy", "People & Body", 14),
    ManGirlGirl("👨‍👧‍👧", "man-girl-girl", "People & Body", 15),
    ManGirl("👨‍👧", "man-girl", "People & Body", 13),
    ManManBoy("👨‍👨‍👦", "man-man-boy", "People & Body", 15),
    ManManBoyBoy("👨‍👨‍👦‍👦", "man-man-boy-boy", "People & Body", 14),
    ManManGirl("👨‍👨‍👧", "man-man-girl", "People & Body", 15),
    ManManGirlBoy("👨‍👨‍👧‍👦", "man-man-girl-boy", "People & Body", 15),
    ManManGirlGirl("👨‍👨‍👧‍👧", "man-man-girl-girl", "People & Body", 14),
    ManWomanBoy("👨‍👩‍👦", "man-woman-boy", "People & Body", 16),
    ManWomanBoyBoy("👨‍👩‍👦‍👦", "man-woman-boy-boy", "People & Body", 13),
    ManWomanGirl("👨‍👩‍👧", "man-woman-girl", "People & Body", 12),
    ManWomanGirlBoy("👨‍👩‍👧‍👦", "man-woman-girl-boy", "People & Body", 12),
    ManWomanGirlGirl("👨‍👩‍👧‍👧", "man-woman-girl-girl", "People & Body", 13),
    MaleTechnologist("👨‍💻", "male-technologist", "People & Body", 11),
    MaleOfficeWorker("👨‍💼", "male-office-worker", "People & Body", 13),
    MaleMechanic("👨‍🔧", "male-mechanic", "People & Body", 13),
    MaleScientist("👨‍🔬", "male-scientist", "People & Body", 13),
    MaleAstronaut("👨‍🚀", "male-astronaut", "People & Body", 13),
    MaleFirefighter("👨‍🚒", "male-firefighter", "People & Body", 13),
    ManWithProbingCane("👨‍🦯", "man_with_probing_cane", "People & Body", null),
    RedHairedMan("👨‍🦰", "red_haired_man", "People & Body", null),
    CurlyHairedMan("👨‍🦱", "curly_haired_man", "People & Body", null),
    BaldMan("👨‍🦲", "bald_man", "People & Body", null),
    WhiteHairedMan("👨‍🦳", "white_haired_man", "People & Body", null),
    ManInMotorizedWheelchair("👨‍🦼", "man_in_motorized_wheelchair", "People & Body", null),
    ManInManualWheelchair("👨‍🦽", "man_in_manual_wheelchair", "People & Body", null),
    MaleDoctor("👨‍⚕️", "male-doctor", "People & Body", 11),
    MaleJudge("👨‍⚖️", "male-judge", "People & Body", 13),
    MalePilot("👨‍✈️", "male-pilot", "People & Body", 12),
    ManHeartMan("👨‍❤️‍👨", "man-heart-man", "People & Body", 12),
    ManKissMan("👨‍❤️‍💋‍👨", "man-kiss-man", "People & Body", 12),
    Man("👨", "man", "People & Body", 9),
    FemaleFarmer("👩‍🌾", "female-farmer", "People & Body", 12),
    FemaleCook("👩‍🍳", "female-cook", "People & Body", 11),
    FemaleStudent("👩‍🎓", "female-student", "People & Body", 10),
    FemaleSinger("👩‍🎤", "female-singer", "People & Body", 12),
    FemaleArtist("👩‍🎨", "female-artist", "People & Body", 13),
    FemaleTeacher("👩‍🏫", "female-teacher", "People & Body", 12),
    FemaleFactoryWorker("👩‍🏭", "female-factory-worker", "People & Body", 14),
    WomanBoyBoy("👩‍👦‍👦", "woman-boy-boy", "People & Body", 14),
    WomanBoy("👩‍👦", "woman-boy", "People & Body", 12),
    WomanGirlBoy("👩‍👧‍👦", "woman-girl-boy", "People & Body", 14),
    WomanGirlGirl("👩‍👧‍👧", "woman-girl-girl", "People & Body", 14),
    WomanGirl("👩‍👧", "woman-girl", "People & Body", 12),
    WomanWomanBoy("👩‍👩‍👦", "woman-woman-boy", "People & Body", 15),
    WomanWomanBoyBoy("👩‍👩‍👦‍👦", "woman-woman-boy-boy", "People & Body", 15),
    WomanWomanGirl("👩‍👩‍👧", "woman-woman-girl", "People & Body", 14),
    WomanWomanGirlBoy("👩‍👩‍👧‍👦", "woman-woman-girl-boy", "People & Body", 14),
    WomanWomanGirlGirl("👩‍👩‍👧‍👧", "woman-woman-girl-girl", "People & Body", 14),
    FemaleTechnologist("👩‍💻", "female-technologist", "People & Body", 11),
    FemaleOfficeWorker("👩‍💼", "female-office-worker", "People & Body", 12),
    FemaleMechanic("👩‍🔧", "female-mechanic", "People & Body", 14),
    FemaleScientist("👩‍🔬", "female-scientist", "People & Body", 12),
    FemaleAstronaut("👩‍🚀", "female-astronaut", "People & Body", 13),
    FemaleFirefighter("👩‍🚒", "female-firefighter", "People & Body", 13),
    WomanWithProbingCane("👩‍🦯", "woman_with_probing_cane", "People & Body", null),
    RedHairedWoman("👩‍🦰", "red_haired_woman", "People & Body", null),
    CurlyHairedWoman("👩‍🦱", "curly_haired_woman", "People & Body", null),
    BaldWoman("👩‍🦲", "bald_woman", "People & Body", null),
    WhiteHairedWoman("👩‍🦳", "white_haired_woman", "People & Body", null),
    WomanInMotorizedWheelchair("👩‍🦼", "woman_in_motorized_wheelchair", "People & Body", null),
    WomanInManualWheelchair("👩‍🦽", "woman_in_manual_wheelchair", "People & Body", null),
    FemaleDoctor("👩‍⚕️", "female-doctor", "People & Body", 11),
    FemaleJudge("👩‍⚖️", "female-judge", "People & Body", 13),
    FemalePilot("👩‍✈️", "female-pilot", "People & Body", 13),
    WomanHeartMan("👩‍❤️‍👨", "woman-heart-man", "People & Body", 14),
    WomanHeartWoman("👩‍❤️‍👩", "woman-heart-woman", "People & Body", 12),
    WomanKissMan("👩‍❤️‍💋‍👨", "woman-kiss-man", "People & Body", 13),
    WomanKissWoman("👩‍❤️‍💋‍👩", "woman-kiss-woman", "People & Body", 10),
    Woman("👩", "woman", "People & Body", 8),
    Family("👪", "family", "People & Body", 11),
    Couple("👫", "couple", "People & Body", 9),
    TwoMenHoldingHands("👬", "two_men_holding_hands", "People & Body", 10),
    TwoWomenHoldingHands("👭", "two_women_holding_hands", "People & Body", 9),
    FemalePoliceOfficer("👮‍♀️", "female-police-officer", "People & Body", null),
    MalePoliceOfficer("👮‍♂️", "male-police-officer", "People & Body", null),
    Cop("👮", "cop", "People & Body", 8),
    WomanWithBunnyEarsPartying("👯‍♀️", "woman-with-bunny-ears-partying", "People & Body", null),
    ManWithBunnyEarsPartying("👯‍♂️", "man-with-bunny-ears-partying", "People & Body", null),
    Dancers("👯", "dancers", "People & Body", 9),
    BrideWithVeil("👰", "bride_with_veil", "People & Body", 10),
    BlondHairedWoman("👱‍♀️", "blond-haired-woman", "People & Body", null),
    BlondHairedMan("👱‍♂️", "blond-haired-man", "People & Body", null),
    PersonWithBlondHair("👱", "person_with_blond_hair", "People & Body", 10),
    ManWithGuaPiMao("👲", "man_with_gua_pi_mao", "People & Body", 12),
    WomanWearingTurban("👳‍♀️", "woman-wearing-turban", "People & Body", null),
    ManWearingTurban("👳‍♂️", "man-wearing-turban", "People & Body", null),
    ManWithTurban("👳", "man_with_turban", "People & Body", 10),
    OlderMan("👴", "older_man", "People & Body", 9),
    OlderWoman("👵", "older_woman", "People & Body", 9),
    Baby("👶", "baby", "People & Body", 7),
    FemaleConstructionWorker("👷‍♀️", "female-construction-worker", "People & Body", null),
    MaleConstructionWorker("👷‍♂️", "male-construction-worker", "People & Body", null),
    ConstructionWorker("👷", "construction_worker", "People & Body", 11),
    Princess("👸", "princess", "People & Body", 8),
    JapaneseOgre("👹", "japanese_ogre", "Smileys & Emotion", 8),
    JapaneseGoblin("👺", "japanese_goblin", "Smileys & Emotion", 10),
    Ghost("👻", "ghost", "Smileys & Emotion", 7),
    Angel("👼", "angel", "People & Body", 7),
    Alien("👽", "alien", "Smileys & Emotion", 8),
    SpaceInvader("👾", "space_invader", "Smileys & Emotion", 10),
    Imp("👿", "imp", "Smileys & Emotion", 8),
    Skull("💀", "skull", "Smileys & Emotion", 6),
    WomanTippingHand("💁‍♀️", "woman-tipping-hand", "People & Body", null),
    ManTippingHand("💁‍♂️", "man-tipping-hand", "People & Body", null),
    InformationDeskPerson("💁", "information_desk_person", "People & Body", 6),
    FemaleGuard("💂‍♀️", "female-guard", "People & Body", null),
    MaleGuard("💂‍♂️", "male-guard", "People & Body", null),
    Guardsman("💂", "guardsman", "People & Body", 12),
    Dancer("💃", "dancer", "People & Body", 5),
    Lipstick("💄", "lipstick", "Objects", 9),
    NailCare("💅", "nail_care", "People & Body", 7),
    WomanGettingMassage("💆‍♀️", "woman-getting-massage", "People & Body", null),
    ManGettingMassage("💆‍♂️", "man-getting-massage", "People & Body", null),
    Massage("💆", "massage", "People & Body", 7),
    WomanGettingHaircut("💇‍♀️", "woman-getting-haircut", "People & Body", null),
    ManGettingHaircut("💇‍♂️", "man-getting-haircut", "People & Body", null),
    Haircut("💇", "haircut", "People & Body", 10),
    Barber("💈", "barber", "Travel & Places", 11),
    Syringe("💉", "syringe", "Objects", 8),
    Pill("💊", "pill", "Objects", 9),
    Kiss("💋", "kiss", "Smileys & Emotion", 5),
    LoveLetter("💌", "love_letter", "Smileys & Emotion", 7),
    Ring("💍", "ring", "Objects", 7),
    Gem("💎", "gem", "Objects", 7),
    Couplekiss("💏", "couplekiss", "People & Body", 8),
    Bouquet("💐", "bouquet", "Animals & Nature", 6),
    CoupleWithHeart("💑", "couple_with_heart", "People & Body", 9),
    Wedding("💒", "wedding", "Travel & Places", 10),
    Heartbeat("💓", "heartbeat", "Smileys & Emotion", 4),
    BrokenHeart("💔", "broken_heart", "Smileys & Emotion", 3),
    TwoHearts("💕", "two_hearts", "Smileys & Emotion", 2),
    SparklingHeart("💖", "sparkling_heart", "Smileys & Emotion", 3),
    Heartpulse("💗", "heartpulse", "Smileys & Emotion", 4),
    Cupid("💘", "cupid", "Smileys & Emotion", 6),
    BlueHeart("💙", "blue_heart", "Smileys & Emotion", 3),
    GreenHeart("💚", "green_heart", "Smileys & Emotion", 4),
    YellowHeart("💛", "yellow_heart", "Smileys & Emotion", 4),
    PurpleHeart("💜", "purple_heart", "Smileys & Emotion", 4),
    GiftHeart("💝", "gift_heart", "Smileys & Emotion", 6),
    RevolvingHearts("💞", "revolving_hearts", "Smileys & Emotion", 4),
    HeartDecoration("💟", "heart_decoration", "Smileys & Emotion", 7),
    DiamondShapeWithADotInside("💠", "diamond_shape_with_a_dot_inside", "Symbols", 9),
    Bulb("💡", "bulb", "Objects", 7),
    Anger("💢", "anger", "Smileys & Emotion", 6),
    Bomb("💣", "bomb", "Smileys & Emotion", 7),
    Zzz("💤", "zzz", "Smileys & Emotion", 8),
    Boom("💥", "boom", "Smileys & Emotion", 5),
    SweatDrops("💦", "sweat_drops", "Smileys & Emotion", 6),
    Droplet("💧", "droplet", "Travel & Places", 7),
    Dash("💨", "dash", "Smileys & Emotion", 7),
    Hankey("💩", "hankey", "Smileys & Emotion", 7),
    Muscle("💪", "muscle", "People & Body", 3),
    Dizzy("💫", "dizzy", "Smileys & Emotion", 6),
    SpeechBalloon("💬", "speech_balloon", "Smileys & Emotion", 9),
    ThoughtBalloon("💭", "thought_balloon", "Smileys & Emotion", 8),
    WhiteFlower("💮", "white_flower", "Animals & Nature", 8),
    Emoji100("💯", "100", "Smileys & Emotion", 4),
    Moneybag("💰", "moneybag", "Objects", 6),
    CurrencyExchange("💱", "currency_exchange", "Objects", 13),
    HeavyDollarSign("💲", "heavy_dollar_sign", "Objects", 10),
    CreditCard("💳", "credit_card", "Objects", 10),
    Yen("💴", "yen", "Objects", 10),
    Dollar("💵", "dollar", "Objects", 8),
    Euro("💶", "euro", "Objects", 10),
    Pound("💷", "pound", "Objects", 11),
    MoneyWithWings("💸", "money_with_wings", "Objects", 7),
    Chart("💹", "chart", "Objects", 13),
    Seat("💺", "seat", "Travel & Places", 12),
    Computer("💻", "computer", "Objects", 9),
    Briefcase("💼", "briefcase", "Objects", 11),
    Minidisc("💽", "minidisc", "Objects", 13),
    FloppyDisk("💾", "floppy_disk", "Objects", 14),
    Cd("💿", "cd", "Objects", 10),
    Dvd("📀", "dvd", "Objects", 11),
    FileFolder("📁", "file_folder", "Objects", 13),
    OpenFileFolder("📂", "open_file_folder", "Objects", 13),
    PageWithCurl("📃", "page_with_curl", "Objects", 12),
    PageFacingUp("📄", "page_facing_up", "Objects", 12),
    Date("📅", "date", "Objects", 11),
    Calendar("📆", "calendar", "Objects", 10),
    CardIndex("📇", "card_index", "Objects", 15),
    ChartWithUpwardsTrend("📈", "chart_with_upwards_trend", "Objects", 10),
    ChartWithDownwardsTrend("📉", "chart_with_downwards_trend", "Objects", 11),
    BarChart("📊", "bar_chart", "Objects", 11),
    Clipboard("📋", "clipboard", "Objects", 12),
    Pushpin("📌", "pushpin", "Objects", 7),
    RoundPushpin("📍", "round_pushpin", "Objects", 7),
    Paperclip("📎", "paperclip", "Objects", 11),
    StraightRuler("📏", "straight_ruler", "Objects", 11),
    TriangularRuler("📐", "triangular_ruler", "Objects", 13),
    BookmarkTabs("📑", "bookmark_tabs", "Objects", 13),
    Ledger("📒", "ledger", "Objects", 12),
    Notebook("📓", "notebook", "Objects", 12),
    NotebookWithDecorativeCover("📔", "notebook_with_decorative_cover", "Objects", 13),
    ClosedBook("📕", "closed_book", "Objects", 11),
    Book("📖", "book", "Objects", 9),
    GreenBook("📗", "green_book", "Objects", 12),
    BlueBook("📘", "blue_book", "Objects", 12),
    OrangeBook("📙", "orange_book", "Objects", 12),
    Books("📚", "books", "Objects", 8),
    NameBadge("📛", "name_badge", "Symbols", 11),
    Scroll("📜", "scroll", "Objects", 12),
    Memo("📝", "memo", "Objects", 9),
    TelephoneReceiver("📞", "telephone_receiver", "Objects", 8),
    Pager("📟", "pager", "Objects", 13),
    Fax("📠", "fax", "Objects", 12),
    SatelliteAntenna("📡", "satellite_antenna", "Objects", 11),
    Loudspeaker("📢", "loudspeaker", "Objects", 8),
    Mega("📣", "mega", "Objects", 7),
    OutboxTray("📤", "outbox_tray", "Objects", 14),
    InboxTray("📥", "inbox_tray", "Objects", 12),
    Package("📦", "package", "Objects", 10),
    EMail("📧", "e-mail", "Objects", 11),
    IncomingEnvelope("📨", "incoming_envelope", "Objects", 11),
    EnvelopeWithArrow("📩", "envelope_with_arrow", "Objects", 9),
    MailboxClosed("📪", "mailbox_closed", "Objects", 14),
    Mailbox("📫", "mailbox", "Objects", 13),
    MailboxWithMail("📬", "mailbox_with_mail", "Objects", 11),
    MailboxWithNoMail("📭", "mailbox_with_no_mail", "Objects", 14),
    Postbox("📮", "postbox", "Objects", 10),
    PostalHorn("📯", "postal_horn", "Objects", 12),
    Newspaper("📰", "newspaper", "Objects", 10),
    Iphone("📱", "iphone", "Objects", 7),
    Calling("📲", "calling", "Objects", 8),
    VibrationMode("📳", "vibration_mode", "Symbols", 13),
    MobilePhoneOff("📴", "mobile_phone_off", "Symbols", 13),
    NoMobilePhones("📵", "no_mobile_phones", "Symbols", 12),
    SignalStrength("📶", "signal_strength", "Symbols", 12),
    Camera("📷", "camera", "Objects", 8),
    CameraWithFlash("📸", "camera_with_flash", "Objects", 7),
    VideoCamera("📹", "video_camera", "Objects", 10),
    Tv("📺", "tv", "Objects", 8),
    Radio("📻", "radio", "Objects", 10),
    Vhs("📼", "vhs", "Objects", 12),
    FilmProjector("📽️", "film_projector", "Objects", 10),
    PrayerBeads("📿", "prayer_beads", "Objects", 11),
    TwistedRightwardsArrows("🔀", "twisted_rightwards_arrows", "Symbols", 13),
    Repeat("🔁", "repeat", "Symbols", 11),
    RepeatOne("🔂", "repeat_one", "Symbols", 13),
    ArrowsClockwise("🔃", "arrows_clockwise", "Symbols", 12),
    ArrowsCounterclockwise("🔄", "arrows_counterclockwise", "Symbols", 10),
    LowBrightness("🔅", "low_brightness", "Symbols", 10),
    HighBrightness("🔆", "high_brightness", "Symbols", 10),
    Mute("🔇", "mute", "Objects", 12),
    Speaker("🔈", "speaker", "Objects", 12),
    Sound("🔉", "sound", "Objects", 12),
    LoudSound("🔊", "loud_sound", "Objects", 8),
    Battery("🔋", "battery", "Objects", 11),
    ElectricPlug("🔌", "electric_plug", "Objects", 11),
    Mag("🔍", "mag", "Objects", 11),
    MagRight("🔎", "mag_right", "Objects", 10),
    LockWithInkPen("🔏", "lock_with_ink_pen", "Objects", 13),
    ClosedLockWithKey("🔐", "closed_lock_with_key", "Objects", 10),
    Key("🔑", "key", "Objects", 10),
    Lock("🔒", "lock", "Objects", 10),
    Unlock("🔓", "unlock", "Objects", 11),
    Bell("🔔", "bell", "Objects", 8),
    NoBell("🔕", "no_bell", "Objects", 12),
    Bookmark("🔖", "bookmark", "Objects", 11),
    Link("🔗", "link", "Objects", 10),
    RadioButton("🔘", "radio_button", "Symbols", 10),
    Back("🔙", "back", "Symbols", 11),
    End("🔚", "end", "Symbols", 12),
    On("🔛", "on", "Symbols", 11),
    Soon("🔜", "soon", "Symbols", 10),
    Top("🔝", "top", "Symbols", 8),
    Underage("🔞", "underage", "Symbols", 8),
    KeycapTen("🔟", "keycap_ten", "Symbols", 12),
    CapitalAbcd("🔠", "capital_abcd", "Symbols", 14),
    Abcd("🔡", "abcd", "Symbols", 15),
    Emoji1234("🔢", "1234", "Symbols", 14),
    Symbols("🔣", "symbols", "Symbols", 15),
    Abc("🔤", "abc", "Symbols", 14),
    Fire("🔥", "fire", "Travel & Places", 3),
    Flashlight("🔦", "flashlight", "Objects", 12),
    Wrench("🔧", "wrench", "Objects", 12),
    Hammer("🔨", "hammer", "Objects", 10),
    NutAndBolt("🔩", "nut_and_bolt", "Objects", 13),
    Hocho("🔪", "hocho", "Food & Drink", 8),
    Gun("🔫", "gun", "Objects", 8),
    Microscope("🔬", "microscope", "Objects", 12),
    Telescope("🔭", "telescope", "Objects", 12),
    CrystalBall("🔮", "crystal_ball", "Activities", 9),
    SixPointedStar("🔯", "six_pointed_star", "Symbols", 12),
    Beginner("🔰", "beginner", "Symbols", 9),
    Trident("🔱", "trident", "Symbols", 10),
    BlackSquareButton("🔲", "black_square_button", "Symbols", 12),
    WhiteSquareButton("🔳", "white_square_button", "Symbols", 12),
    RedCircle("🔴", "red_circle", "Symbols", 6),
    LargeBlueCircle("🔵", "large_blue_circle", "Symbols", 7),
    LargeOrangeDiamond("🔶", "large_orange_diamond", "Symbols", 9),
    LargeBlueDiamond("🔷", "large_blue_diamond", "Symbols", 8),
    SmallOrangeDiamond("🔸", "small_orange_diamond", "Symbols", 9),
    SmallBlueDiamond("🔹", "small_blue_diamond", "Symbols", 8),
    SmallRedTriangle("🔺", "small_red_triangle", "Symbols", 10),
    SmallRedTriangleDown("🔻", "small_red_triangle_down", "Symbols", 9),
    ArrowUpSmall("🔼", "arrow_up_small", "Symbols", 12),
    ArrowDownSmall("🔽", "arrow_down_small", "Symbols", 10),
    OmSymbol("🕉️", "om_symbol", "Symbols", 11),
    DoveOfPeace("🕊️", "dove_of_peace", "Animals & Nature", 8),
    Kaaba("🕋", "kaaba", "Travel & Places", 10),
    Mosque("🕌", "mosque", "Travel & Places", 10),
    Synagogue("🕍", "synagogue", "Travel & Places", 14),
    MenorahWithNineBranches("🕎", "menorah_with_nine_branches", "Symbols", 13),
    Clock1("🕐", "clock1", "Travel & Places", 13),
    Clock2("🕑", "clock2", "Travel & Places", 13),
    Clock3("🕒", "clock3", "Travel & Places", 12),
    Clock4("🕓", "clock4", "Travel & Places", 13),
    Clock5("🕔", "clock5", "Travel & Places", 13),
    Clock6("🕕", "clock6", "Travel & Places", 13),
    Clock7("🕖", "clock7", "Travel & Places", 13),
    Clock8("🕗", "clock8", "Travel & Places", 13),
    Clock9("🕘", "clock9", "Travel & Places", 13),
    Clock10("🕙", "clock10", "Travel & Places", 13),
    Clock11("🕚", "clock11", "Travel & Places", 14),
    Clock12("🕛", "clock12", "Travel & Places", 12),
    Clock130("🕜", "clock130", "Travel & Places", 15),
    Clock230("🕝", "clock230", "Travel & Places", 15),
    Clock330("🕞", "clock330", "Travel & Places", 15),
    Clock430("🕟", "clock430", "Travel & Places", 14),
    Clock530("🕠", "clock530", "Travel & Places", 14),
    Clock630("🕡", "clock630", "Travel & Places", 15),
    Clock730("🕢", "clock730", "Travel & Places", 15),
    Clock830("🕣", "clock830", "Travel & Places", 15),
    Clock930("🕤", "clock930", "Travel & Places", 15),
    Clock1030("🕥", "clock1030", "Travel & Places", 15),
    Clock1130("🕦", "clock1130", "Travel & Places", 15),
    Clock1230("🕧", "clock1230", "Travel & Places", 15),
    Candle("🕯️", "candle", "Objects", 10),
    MantelpieceClock("🕰️", "mantelpiece_clock", "Travel & Places", 12),
    Hole("🕳️", "hole", "Smileys & Emotion", 12),
    ManInBusinessSuitLevitating("🕴️", "man_in_business_suit_levitating", "People & Body", 11),
    FemaleDetective("🕵️‍♀️", "female-detective", "People & Body", null),
    MaleDetective("🕵️‍♂️", "male-detective", "People & Body", null),
    SleuthOrSpy("🕵️", "sleuth_or_spy", "People & Body", 10),
    DarkSunglasses("🕶️", "dark_sunglasses", "Objects", 10),
    Spider("🕷️", "spider", "Animals & Nature", 10),
    SpiderWeb("🕸️", "spider_web", "Animals & Nature", 11),
    Joystick("🕹️", "joystick", "Activities", 11),
    ManDancing("🕺", "man_dancing", "People & Body", 7),
    LinkedPaperclips("🖇️", "linked_paperclips", "Objects", 11),
    LowerLeftBallpointPen("🖊️", "lower_left_ballpoint_pen", "Objects", 11),
    LowerLeftFountainPen("🖋️", "lower_left_fountain_pen", "Objects", 11),
    LowerLeftPaintbrush("🖌️", "lower_left_paintbrush", "Objects", 11),
    LowerLeftCrayon("🖍️", "lower_left_crayon", "Objects", 12),
    RaisedHandWithFingersSplayed("🖐️", "raised_hand_with_fingers_splayed", "People & Body", 8),
    MiddleFinger("🖕", "middle_finger", "People & Body", 6),
    SpockHand("🖖", "spock-hand", "People & Body", 10),
    BlackHeart("🖤", "black_heart", "Smileys & Emotion", 4),
    DesktopComputer("🖥️", "desktop_computer", "Objects", 11),
    Printer("🖨️", "printer", "Objects", 14),
    ThreeButtonMouse("🖱️", "three_button_mouse", "Objects", 13),
    Trackball("🖲️", "trackball", "Objects", 14),
    FrameWithPicture("🖼️", "frame_with_picture", "Activities", 11),
    CardIndexDividers("🗂️", "card_index_dividers", "Objects", 14),
    CardFileBox("🗃️", "card_file_box", "Objects", 15),
    FileCabinet("🗄️", "file_cabinet", "Objects", 15),
    Wastebasket("🗑️", "wastebasket", "Objects", 11),
    SpiralNotePad("🗒️", "spiral_note_pad", "Objects", 13),
    SpiralCalendarPad("🗓️", "spiral_calendar_pad", "Objects", 10),
    Compression("🗜️", "compression", "Objects", 15),
    OldKey("🗝️", "old_key", "Objects", 10),
    RolledUpNewspaper("🗞️", "rolled_up_newspaper", "Objects", 11),
    DaggerKnife("🗡️", "dagger_knife", "Objects", 10),
    SpeakingHeadInSilhouette("🗣️", "speaking_head_in_silhouette", "People & Body", 6),
    LeftSpeechBubble("🗨️", "left_speech_bubble", "Smileys & Emotion", 11),
    RightAngerBubble("🗯️", "right_anger_bubble", "Smileys & Emotion", 11),
    BallotBoxWithBallot("🗳️", "ballot_box_with_ballot", "Objects", 11),
    WorldMap("🗺️", "world_map", "Travel & Places", 11),
    MountFuji("🗻", "mount_fuji", "Travel & Places", 10),
    TokyoTower("🗼", "tokyo_tower", "Travel & Places", 11),
    StatueOfLiberty("🗽", "statue_of_liberty", "Travel & Places", 10),
    Japan("🗾", "japan", "Travel & Places", 12),
    Moyai("🗿", "moyai", "Objects", 11),
    Grinning("😀", "grinning", "Smileys & Emotion", 4),
    Grin("😁", "grin", "Smileys & Emotion", 3),
    Joy("😂", "joy", "Smileys & Emotion", 0),
    Smiley("😃", "smiley", "Smileys & Emotion", 4),
    Smile("😄", "smile", "Smileys & Emotion", 4),
    SweatSmile("😅", "sweat_smile", "Smileys & Emotion", 3),
    Laughing("😆", "laughing", "Smileys & Emotion", 3),
    Innocent("😇", "innocent", "Smileys & Emotion", 4),
    SmilingImp("😈", "smiling_imp", "Smileys & Emotion", 5),
    Wink("😉", "wink", "Smileys & Emotion", 3),
    Blush("😊", "blush", "Smileys & Emotion", 2),
    Yum("😋", "yum", "Smileys & Emotion", 4),
    Relieved("😌", "relieved", "Smileys & Emotion", 4),
    HeartEyes("😍", "heart_eyes", "Smileys & Emotion", 1),
    Sunglasses("😎", "sunglasses", "Smileys & Emotion", 4),
    Smirk("😏", "smirk", "Smileys & Emotion", 4),
    NeutralFace("😐", "neutral_face", "Smileys & Emotion", 6),
    Expressionless("😑", "expressionless", "Smileys & Emotion", 5),
    Unamused("😒", "unamused", "Smileys & Emotion", 4),
    Sweat("😓", "sweat", "Smileys & Emotion", 5),
    Pensive("😔", "pensive", "Smileys & Emotion", 4),
    Confused("😕", "confused", "Smileys & Emotion", 6),
    Confounded("😖", "confounded", "Smileys & Emotion", 7),
    Kissing("😗", "kissing", "Smileys & Emotion", 7),
    KissingHeart("😘", "kissing_heart", "Smileys & Emotion", 2),
    KissingSmilingEyes("😙", "kissing_smiling_eyes", "Smileys & Emotion", 7),
    KissingClosedEyes("😚", "kissing_closed_eyes", "Smileys & Emotion", 5),
    StuckOutTongue("😛", "stuck_out_tongue", "Smileys & Emotion", 6),
    StuckOutTongueWinkingEye("😜", "stuck_out_tongue_winking_eye", "Smileys & Emotion", 5),
    StuckOutTongueClosedEyes("😝", "stuck_out_tongue_closed_eyes", "Smileys & Emotion", 5),
    Disappointed("😞", "disappointed", "Smileys & Emotion", 5),
    Worried("😟", "worried", "Smileys & Emotion", 7),
    Angry("😠", "angry", "Smileys & Emotion", 6),
    Rage("😡", "rage", "Smileys & Emotion", 5),
    Cry("😢", "cry", "Smileys & Emotion", 3),
    Persevere("😣", "persevere", "Smileys & Emotion", 6),
    Triumph("😤", "triumph", "Smileys & Emotion", 6),
    DisappointedRelieved("😥", "disappointed_relieved", "Smileys & Emotion", 5),
    Frowning("😦", "frowning", "Smileys & Emotion", 8),
    Anguished("😧", "anguished", "Smileys & Emotion", 8),
    Fearful("😨", "fearful", "Smileys & Emotion", 7),
    Weary("😩", "weary", "Smileys & Emotion", 5),
    Sleepy("😪", "sleepy", "Smileys & Emotion", 5),
    TiredFace("😫", "tired_face", "Smileys & Emotion", 6),
    Grimacing("😬", "grimacing", "Smileys & Emotion", 5),
    Sob("😭", "sob", "Smileys & Emotion", 2),
    OpenMouth("😮", "open_mouth", "Smileys & Emotion", 6),
    Hushed("😯", "hushed", "Smileys & Emotion", 7),
    ColdSweat("😰", "cold_sweat", "Smileys & Emotion", 6),
    Scream("😱", "scream", "Smileys & Emotion", 4),
    Astonished("😲", "astonished", "Smileys & Emotion", 6),
    Flushed("😳", "flushed", "Smileys & Emotion", 5),
    Sleeping("😴", "sleeping", "Smileys & Emotion", 5),
    DizzyFace("😵", "dizzy_face", "Smileys & Emotion", 7),
    NoMouth("😶", "no_mouth", "Smileys & Emotion", 6),
    Mask("😷", "mask", "Smileys & Emotion", 7),
    SmileCat("😸", "smile_cat", "Smileys & Emotion", 9),
    JoyCat("😹", "joy_cat", "Smileys & Emotion", 6),
    SmileyCat("😺", "smiley_cat", "Smileys & Emotion", 10),
    HeartEyesCat("😻", "heart_eyes_cat", "Smileys & Emotion", 5),
    SmirkCat("😼", "smirk_cat", "Smileys & Emotion", 9),
    KissingCat("😽", "kissing_cat", "Smileys & Emotion", 9),
    PoutingCat("😾", "pouting_cat", "Smileys & Emotion", 10),
    CryingCatFace("😿", "crying_cat_face", "Smileys & Emotion", 8),
    ScreamCat("🙀", "scream_cat", "Smileys & Emotion", 8),
    SlightlyFrowningFace("🙁", "slightly_frowning_face", "Smileys & Emotion", 7),
    SlightlySmilingFace("🙂", "slightly_smiling_face", "Smileys & Emotion", 4),
    UpsideDownFace("🙃", "upside_down_face", "Smileys & Emotion", 5),
    FaceWithRollingEyes("🙄", "face_with_rolling_eyes", "Smileys & Emotion", 3),
    WomanGesturingNo("🙅‍♀️", "woman-gesturing-no", "People & Body", null),
    ManGesturingNo("🙅‍♂️", "man-gesturing-no", "People & Body", null),
    NoGood("🙅", "no_good", "People & Body", 7),
    WomanGesturingOk("🙆‍♀️", "woman-gesturing-ok", "People & Body", null),
    ManGesturingOk("🙆‍♂️", "man-gesturing-ok", "People & Body", null),
    OkWoman("🙆", "ok_woman", "People & Body", 6),
    WomanBowing("🙇‍♀️", "woman-bowing", "People & Body", null),
    ManBowing("🙇‍♂️", "man-bowing", "People & Body", null),
    Bow("🙇", "bow", "People & Body", 7),
    SeeNoEvil("🙈", "see_no_evil", "Smileys & Emotion", 4),
    HearNoEvil("🙉", "hear_no_evil", "Smileys & Emotion", 8),
    SpeakNoEvil("🙊", "speak_no_evil", "Smileys & Emotion", 6),
    WomanRaisingHand("🙋‍♀️", "woman-raising-hand", "People & Body", null),
    ManRaisingHand("🙋‍♂️", "man-raising-hand", "People & Body", null),
    RaisingHand("🙋", "raising_hand", "People & Body", 5),
    RaisedHands("🙌", "raised_hands", "People & Body", 4),
    WomanFrowning("🙍‍♀️", "woman-frowning", "People & Body", null),
    ManFrowning("🙍‍♂️", "man-frowning", "People & Body", null),
    PersonFrowning("🙍", "person_frowning", "People & Body", 10),
    WomanPouting("🙎‍♀️", "woman-pouting", "People & Body", null),
    ManPouting("🙎‍♂️", "man-pouting", "People & Body", null),
    PersonWithPoutingFace("🙎", "person_with_pouting_face", "People & Body", 10),
    Pray("🙏", "pray", "People & Body", 2),
    Rocket("🚀", "rocket", "Travel & Places", 7),
    Helicopter("🚁", "helicopter", "Travel & Places", 11),
    SteamLocomotive("🚂", "steam_locomotive", "Travel & Places", 10),
    RailwayCar("🚃", "railway_car", "Travel & Places", 10),
    BullettrainSide("🚄", "bullettrain_side", "Travel & Places", 11),
    BullettrainFront("🚅", "bullettrain_front", "Travel & Places", 11),
    Train2("🚆", "train2", "Travel & Places", 13),
    Metro("🚇", "metro", "Travel & Places", 12),
    LightRail("🚈", "light_rail", "Travel & Places", 13),
    Station("🚉", "station", "Travel & Places", 12),
    Tram("🚊", "tram", "Travel & Places", 13),
    Train("🚋", "train", "Travel & Places", 12),
    Bus("🚌", "bus", "Travel & Places", 10),
    OncomingBus("🚍", "oncoming_bus", "Travel & Places", 12),
    Trolleybus("🚎", "trolleybus", "Travel & Places", 13),
    Busstop("🚏", "busstop", "Travel & Places", 14),
    Minibus("🚐", "minibus", "Travel & Places", 12),
    Ambulance("🚑", "ambulance", "Travel & Places", 10),
    FireEngine("🚒", "fire_engine", "Travel & Places", 10),
    PoliceCar("🚓", "police_car", "Travel & Places", 10),
    OncomingPoliceCar("🚔", "oncoming_police_car", "Travel & Places", 10),
    Taxi("🚕", "taxi", "Travel & Places", 11),
    OncomingTaxi("🚖", "oncoming_taxi", "Travel & Places", 12),
    Car("🚗", "car", "Travel & Places", 8),
    OncomingAutomobile("🚘", "oncoming_automobile", "Travel & Places", 10),
    BlueCar("🚙", "blue_car", "Travel & Places", 10),
    Truck("🚚", "truck", "Travel & Places", 11),
    ArticulatedLorry("🚛", "articulated_lorry", "Travel & Places", 11),
    Tractor("🚜", "tractor", "Travel & Places", 12),
    Monorail("🚝", "monorail", "Travel & Places", 14),
    MountainRailway("🚞", "mountain_railway", "Travel & Places", 13),
    SuspensionRailway("🚟", "suspension_railway", "Travel & Places", 14),
    MountainCableway("🚠", "mountain_cableway", "Travel & Places", 14),
    AerialTramway("🚡", "aerial_tramway", "Travel & Places", 13),
    Ship("🚢", "ship", "Travel & Places", 10),
    WomanRowingBoat("🚣‍♀️", "woman-rowing-boat", "People & Body", null),
    ManRowingBoat("🚣‍♂️", "man-rowing-boat", "People & Body", null),
    Rowboat("🚣", "rowboat", "People & Body", 11),
    Speedboat("🚤", "speedboat", "Travel & Places", 10),
    TrafficLight("🚥", "traffic_light", "Travel & Places", 12),
    VerticalTrafficLight("🚦", "vertical_traffic_light", "Travel & Places", 11),
    Construction("🚧", "construction", "Travel & Places", 11),
    RotatingLight("🚨", "rotating_light", "Travel & Places", 7),
    TriangularFlagOnPost("🚩", "triangular_flag_on_post", "Flags", 7),
    Door("🚪", "door", "Objects", 11),
    NoEntrySign("🚫", "no_entry_sign", "Symbols", 8),
    Smoking("🚬", "smoking", "Objects", 9),
    NoSmoking("🚭", "no_smoking", "Symbols", 12),
    PutLitterInItsPlace("🚮", "put_litter_in_its_place", "Symbols", 9),
    DoNotLitter("🚯", "do_not_litter", "Symbols", 12),
    PotableWater("🚰", "potable_water", "Symbols", 12),
    NonPotableWater("🚱", "non-potable_water", "Symbols", 14),
    Bike("🚲", "bike", "Travel & Places", 10),
    NoBicycles("🚳", "no_bicycles", "Symbols", 13),
    WomanBiking("🚴‍♀️", "woman-biking", "People & Body", null),
    ManBiking("🚴‍♂️", "man-biking", "People & Body", null),
    Bicyclist("🚴", "bicyclist", "People & Body", 9),
    WomanMountainBiking("🚵‍♀️", "woman-mountain-biking", "People & Body", null),
    ManMountainBiking("🚵‍♂️", "man-mountain-biking", "People & Body", null),
    MountainBicyclist("🚵", "mountain_bicyclist", "People & Body", 12),
    WomanWalking("🚶‍♀️", "woman-walking", "People & Body", null),
    ManWalking("🚶‍♂️", "man-walking", "People & Body", null),
    Walking("🚶", "walking", "People & Body", 6),
    NoPedestrians("🚷", "no_pedestrians", "Symbols", 13),
    ChildrenCrossing("🚸", "children_crossing", "Symbols", 13),
    Mens("🚹", "mens", "Symbols", 11),
    Womens("🚺", "womens", "Symbols", 11),
    Restroom("🚻", "restroom", "Symbols", 11),
    BabySymbol("🚼", "baby_symbol", "Symbols", 12),
    Toilet("🚽", "toilet", "Objects", 11),
    Wc("🚾", "wc", "Symbols", 12),
    Shower("🚿", "shower", "Objects", 10),
    Bath("🛀", "bath", "People & Body", 11),
    Bathtub("🛁", "bathtub", "Objects", 11),
    PassportControl("🛂", "passport_control", "Symbols", 12),
    Customs("🛃", "customs", "Symbols", 12),
    BaggageClaim("🛄", "baggage_claim", "Symbols", 13),
    LeftLuggage("🛅", "left_luggage", "Symbols", 12),
    CouchAndLamp("🛋️", "couch_and_lamp", "Objects", 13),
    SleepingAccommodation("🛌", "sleeping_accommodation", "People & Body", 10),
    ShoppingBags("🛍️", "shopping_bags", "Objects", 11),
    BellhopBell("🛎️", "bellhop_bell", "Travel & Places", 11),
    Bed("🛏️", "bed", "Objects", 11),
    PlaceOfWorship("🛐", "place_of_worship", "Symbols", 11),
    OctagonalSign("🛑", "octagonal_sign", "Travel & Places", 9),
    ShoppingTrolley("🛒", "shopping_trolley", "Objects", 11),
    HinduTemple("🛕", "hindu_temple", "Travel & Places", null),
    HammerAndWrench("🛠️", "hammer_and_wrench", "Objects", 12),
    Shield("🛡️", "shield", "Objects", 10),
    OilDrum("🛢️", "oil_drum", "Travel & Places", 12),
    Motorway("🛣️", "motorway", "Travel & Places", 13),
    RailwayTrack("🛤️", "railway_track", "Travel & Places", 13),
    MotorBoat("🛥️", "motor_boat", "Travel & Places", 13),
    SmallAirplane("🛩️", "small_airplane", "Travel & Places", 11),
    AirplaneDeparture("🛫", "airplane_departure", "Travel & Places", 10),
    AirplaneArriving("🛬", "airplane_arriving", "Travel & Places", 12),
    Satellite("🛰️", "satellite", "Travel & Places", 12),
    PassengerShip("🛳️", "passenger_ship", "Travel & Places", 12),
    Scooter("🛴", "scooter", "Travel & Places", 12),
    MotorScooter("🛵", "motor_scooter", "Travel & Places", 11),
    Canoe("🛶", "canoe", "Travel & Places", 13),
    Sled("🛷", "sled", "Activities", 15),
    FlyingSaucer("🛸", "flying_saucer", "Travel & Places", 11),
    Skateboard("🛹", "skateboard", "Travel & Places", null),
    AutoRickshaw("🛺", "auto_rickshaw", "Travel & Places", null),
    LargeOrangeCircle("🟠", "large_orange_circle", "Symbols", null),
    LargeYellowCircle("🟡", "large_yellow_circle", "Symbols", null),
    LargeGreenCircle("🟢", "large_green_circle", "Symbols", null),
    LargePurpleCircle("🟣", "large_purple_circle", "Symbols", null),
    LargeBrownCircle("🟤", "large_brown_circle", "Symbols", null),
    LargeRedSquare("🟥", "large_red_square", "Symbols", null),
    LargeBlueSquare("🟦", "large_blue_square", "Symbols", null),
    LargeOrangeSquare("🟧", "large_orange_square", "Symbols", null),
    LargeYellowSquare("🟨", "large_yellow_square", "Symbols", null),
    LargeGreenSquare("🟩", "large_green_square", "Symbols", null),
    LargePurpleSquare("🟪", "large_purple_square", "Symbols", null),
    LargeBrownSquare("🟫", "large_brown_square", "Symbols", null),
    WhiteHeart("🤍", "white_heart", "Smileys & Emotion", null),
    BrownHeart("🤎", "brown_heart", "Smileys & Emotion", null),
    PinchingHand("🤏", "pinching_hand", "People & Body", null),
    ZipperMouthFace("🤐", "zipper_mouth_face", "Smileys & Emotion", 7),
    MoneyMouthFace("🤑", "money_mouth_face", "Smileys & Emotion", 7),
    FaceWithThermometer("🤒", "face_with_thermometer", "Smileys & Emotion", 8),
    NerdFace("🤓", "nerd_face", "Smileys & Emotion", 7),
    ThinkingFace("🤔", "thinking_face", "Smileys & Emotion", 3),
    FaceWithHeadBandage("🤕", "face_with_head_bandage", "Smileys & Emotion", 8),
    RobotFace("🤖", "robot_face", "Smileys & Emotion", 10),
    HuggingFace("🤗", "hugging_face", "Smileys & Emotion", 3),
    TheHorns("🤘", "the_horns", "People & Body", 5),
    CallMeHand("🤙", "call_me_hand", "People & Body", 6),
    RaisedBackOfHand("🤚", "raised_back_of_hand", "People & Body", 8),
    LeftFacingFist("🤛", "left-facing_fist", "People & Body", 9),
    RightFacingFist("🤜", "right-facing_fist", "People & Body", 9),
    Handshake("🤝", "handshake", "People & Body", 6),
    CrossedFingers("🤞", "crossed_fingers", "People & Body", 6),
    ILoveYouHandSign("🤟", "i_love_you_hand_sign", "People & Body", 7),
    FaceWithCowboyHat("🤠", "face_with_cowboy_hat", "Smileys & Emotion", 7),
    ClownFace("🤡", "clown_face", "Smileys & Emotion", 8),
    NauseatedFace("🤢", "nauseated_face", "Smileys & Emotion", 7),
    RollingOnTheFloorLaughing("🤣", "rolling_on_the_floor_laughing", "Smileys & Emotion", 1),
    DroolingFace("🤤", "drooling_face", "Smileys & Emotion", 5),
    LyingFace("🤥", "lying_face", "Smileys & Emotion", 10),
    WomanFacepalming("🤦‍♀️", "woman-facepalming", "People & Body", null),
    ManFacepalming("🤦‍♂️", "man-facepalming", "People & Body", null),
    FacePalm("🤦", "face_palm", "People & Body", 4),
    SneezingFace("🤧", "sneezing_face", "Smileys & Emotion", 7),
    FaceWithRaisedEyebrow("🤨", "face_with_raised_eyebrow", "Smileys & Emotion", 6),
    StarStruck("🤩", "star-struck", "Smileys & Emotion", 4),
    ZanyFace("🤪", "zany_face", "Smileys & Emotion", 5),
    ShushingFace("🤫", "shushing_face", "Smileys & Emotion", 6),
    FaceWithSymbolsOnMouth("🤬", "face_with_symbols_on_mouth", "Smileys & Emotion", 7),
    FaceWithHandOverMouth("🤭", "face_with_hand_over_mouth", "Smileys & Emotion", 4),
    FaceVomiting("🤮", "face_vomiting", "Smileys & Emotion", 7),
    ExplodingHead("🤯", "exploding_head", "Smileys & Emotion", 7),
    PregnantWoman("🤰", "pregnant_woman", "People & Body", 9),
    BreastFeeding("🤱", "breast-feeding", "People & Body", 10),
    PalmsUpTogether("🤲", "palms_up_together", "People & Body", 7),
    Selfie("🤳", "selfie", "People & Body", 10),
    Prince("🤴", "prince", "People & Body", 10),
    ManInTuxedo("🤵", "man_in_tuxedo", "People & Body", 11),
    MrsClaus("🤶", "mrs_claus", "People & Body", 13),
    WomanShrugging("🤷‍♀️", "woman-shrugging", "People & Body", null),
    ManShrugging("🤷‍♂️", "man-shrugging", "People & Body", null),
    Shrug("🤷", "shrug", "People & Body", 4),
    WomanCartwheeling("🤸‍♀️", "woman-cartwheeling", "People & Body", null),
    ManCartwheeling("🤸‍♂️", "man-cartwheeling", "People & Body", null),
    PersonDoingCartwheel("🤸", "person_doing_cartwheel", "People & Body", 8),
    WomanJuggling("🤹‍♀️", "woman-juggling", "People & Body", null),
    ManJuggling("🤹‍♂️", "man-juggling", "People & Body", null),
    Juggling("🤹", "juggling", "People & Body", 11),
    Fencer("🤺", "fencer", "People & Body", 11),
    WomanWrestling("🤼‍♀️", "woman-wrestling", "People & Body", null),
    ManWrestling("🤼‍♂️", "man-wrestling", "People & Body", null),
    Wrestlers("🤼", "wrestlers", "People & Body", 11),
    WomanPlayingWaterPolo("🤽‍♀️", "woman-playing-water-polo", "People & Body", null),
    ManPlayingWaterPolo("🤽‍♂️", "man-playing-water-polo", "People & Body", null),
    WaterPolo("🤽", "water_polo", "People & Body", 13),
    WomanPlayingHandball("🤾‍♀️", "woman-playing-handball", "People & Body", null),
    ManPlayingHandball("🤾‍♂️", "man-playing-handball", "People & Body", null),
    Handball("🤾", "handball", "People & Body", 11),
    DivingMask("🤿", "diving_mask", "Activities", null),
    WiltedFlower("🥀", "wilted_flower", "Animals & Nature", 7),
    DrumWithDrumsticks("🥁", "drum_with_drumsticks", "Objects", 9),
    ClinkingGlasses("🥂", "clinking_glasses", "Food & Drink", 7),
    TumblerGlass("🥃", "tumbler_glass", "Food & Drink", 9),
    Spoon("🥄", "spoon", "Food & Drink", 11),
    GoalNet("🥅", "goal_net", "Activities", 11),
    FirstPlaceMedal("🥇", "first_place_medal", "Activities", 8),
    SecondPlaceMedal("🥈", "second_place_medal", "Activities", 11),
    ThirdPlaceMedal("🥉", "third_place_medal", "Activities", 11),
    BoxingGlove("🥊", "boxing_glove", "Activities", 9),
    MartialArtsUniform("🥋", "martial_arts_uniform", "Activities", 10),
    CurlingStone("🥌", "curling_stone", "Activities", 14),
    Lacrosse("🥍", "lacrosse", "Activities", null),
    Softball("🥎", "softball", "Activities", null),
    FlyingDisc("🥏", "flying_disc", "Activities", null),
    Croissant("🥐", "croissant", "Food & Drink", 10),
    Avocado("🥑", "avocado", "Food & Drink", 10),
    Cucumber("🥒", "cucumber", "Food & Drink", 10),
    Bacon("🥓", "bacon", "Food & Drink", 10),
    Potato("🥔", "potato", "Food & Drink", 10),
    Carrot("🥕", "carrot", "Food & Drink", 9),
    BaguetteBread("🥖", "baguette_bread", "Food & Drink", 11),
    GreenSalad("🥗", "green_salad", "Food & Drink", 10),
    ShallowPanOfFood("🥘", "shallow_pan_of_food", "Food & Drink", 11),
    StuffedFlatbread("🥙", "stuffed_flatbread", "Food & Drink", 12),
    Egg("🥚", "egg", "Food & Drink", 10),
    GlassOfMilk("🥛", "glass_of_milk", "Food & Drink", 10),
    Peanuts("🥜", "peanuts", "Food & Drink", 11),
    Kiwifruit("🥝", "kiwifruit", "Food & Drink", 10),
    Pancakes("🥞", "pancakes", "Food & Drink", 10),
    Dumpling("🥟", "dumpling", "Food & Drink", 11),
    FortuneCookie("🥠", "fortune_cookie", "Food & Drink", 13),
    TakeoutBox("🥡", "takeout_box", "Food & Drink", 13),
    Chopsticks("🥢", "chopsticks", "Food & Drink", 11),
    BowlWithSpoon("🥣", "bowl_with_spoon", "Food & Drink", 12),
    CupWithStraw("🥤", "cup_with_straw", "Food & Drink", 10),
    Coconut("🥥", "coconut", "Food & Drink", 11),
    Broccoli("🥦", "broccoli", "Food & Drink", 9),
    Pie("🥧", "pie", "Food & Drink", 11),
    Pretzel("🥨", "pretzel", "Food & Drink", 12),
    CutOfMeat("🥩", "cut_of_meat", "Food & Drink", 9),
    Sandwich("🥪", "sandwich", "Food & Drink", 11),
    CannedFood("🥫", "canned_food", "Food & Drink", 12),
    LeafyGreen("🥬", "leafy_green", "Food & Drink", null),
    Mango("🥭", "mango", "Food & Drink", null),
    MoonCake("🥮", "moon_cake", "Food & Drink", null),
    Bagel("🥯", "bagel", "Food & Drink", null),
    SmilingFaceWith3Hearts("🥰", "smiling_face_with_3_hearts", "Smileys & Emotion", null),
    YawningFace("🥱", "yawning_face", "Smileys & Emotion", null),
    PartyingFace("🥳", "partying_face", "Smileys & Emotion", null),
    WoozyFace("🥴", "woozy_face", "Smileys & Emotion", null),
    HotFace("🥵", "hot_face", "Smileys & Emotion", null),
    ColdFace("🥶", "cold_face", "Smileys & Emotion", null),
    PleadingFace("🥺", "pleading_face", "Smileys & Emotion", null),
    Sari("🥻", "sari", "Objects", null),
    LabCoat("🥼", "lab_coat", "Objects", null),
    Goggles("🥽", "goggles", "Objects", null),
    HikingBoot("🥾", "hiking_boot", "Objects", null),
    WomansFlatShoe("🥿", "womans_flat_shoe", "Objects", null),
    Crab("🦀", "crab", "Food & Drink", 9),
    LionFace("🦁", "lion_face", "Animals & Nature", 9),
    Scorpion("🦂", "scorpion", "Animals & Nature", 11),
    Turkey("🦃", "turkey", "Animals & Nature", 12),
    UnicornFace("🦄", "unicorn_face", "Animals & Nature", 8),
    Eagle("🦅", "eagle", "Animals & Nature", 9),
    Duck("🦆", "duck", "Animals & Nature", 10),
    Bat("🦇", "bat", "Animals & Nature", 11),
    Shark("🦈", "shark", "Animals & Nature", 10),
    Owl("🦉", "owl", "Animals & Nature", 10),
    FoxFace("🦊", "fox_face", "Animals & Nature", 10),
    Butterfly("🦋", "butterfly", "Animals & Nature", 7),
    Deer("🦌", "deer", "Animals & Nature", 11),
    Gorilla("🦍", "gorilla", "Animals & Nature", 10),
    Lizard("🦎", "lizard", "Animals & Nature", 11),
    Rhinoceros("🦏", "rhinoceros", "Animals & Nature", 12),
    Shrimp("🦐", "shrimp", "Food & Drink", 9),
    Squid("🦑", "squid", "Food & Drink", 10),
    GiraffeFace("🦒", "giraffe_face", "Animals & Nature", 11),
    ZebraFace("🦓", "zebra_face", "Animals & Nature", 11),
    Hedgehog("🦔", "hedgehog", "Animals & Nature", 12),
    Sauropod("🦕", "sauropod", "Animals & Nature", 11),
    TRex("🦖", "t-rex", "Animals & Nature", 10),
    Cricket("🦗", "cricket", "Animals & Nature", 11),
    Kangaroo("🦘", "kangaroo", "Animals & Nature", null),
    Llama("🦙", "llama", "Animals & Nature", null),
    Peacock("🦚", "peacock", "Animals & Nature", null),
    Hippopotamus("🦛", "hippopotamus", "Animals & Nature", null),
    Parrot("🦜", "parrot", "Animals & Nature", null),
    Raccoon("🦝", "raccoon", "Animals & Nature", null),
    Lobster("🦞", "lobster", "Food & Drink", null),
    Mosquito("🦟", "mosquito", "Animals & Nature", null),
    Microbe("🦠", "microbe", "Animals & Nature", null),
    Badger("🦡", "badger", "Animals & Nature", null),
    Swan("🦢", "swan", "Animals & Nature", null),
    Sloth("🦥", "sloth", "Animals & Nature", null),
    Otter("🦦", "otter", "Animals & Nature", null),
    Orangutan("🦧", "orangutan", "Animals & Nature", null),
    Skunk("🦨", "skunk", "Animals & Nature", null),
    Flamingo("🦩", "flamingo", "Animals & Nature", null),
    Oyster("🦪", "oyster", "Food & Drink", null),
    GuideDog("🦮", "guide_dog", "Animals & Nature", null),
    ProbingCane("🦯", "probing_cane", "Objects", null),
    Bone("🦴", "bone", "People & Body", null),
    Leg("🦵", "leg", "People & Body", null),
    Foot("🦶", "foot", "People & Body", null),
    Tooth("🦷", "tooth", "People & Body", null),
    FemaleSuperhero("🦸‍♀️", "female_superhero", "People & Body", null),
    MaleSuperhero("🦸‍♂️", "male_superhero", "People & Body", null),
    Superhero("🦸", "superhero", "People & Body", null),
    FemaleSupervillain("🦹‍♀️", "female_supervillain", "People & Body", null),
    MaleSupervillain("🦹‍♂️", "male_supervillain", "People & Body", null),
    Supervillain("🦹", "supervillain", "People & Body", null),
    SafetyVest("🦺", "safety_vest", "Objects", null),
    EarWithHearingAid("🦻", "ear_with_hearing_aid", "People & Body", null),
    MotorizedWheelchair("🦼", "motorized_wheelchair", "Travel & Places", null),
    ManualWheelchair("🦽", "manual_wheelchair", "Travel & Places", null),
    MechanicalArm("🦾", "mechanical_arm", "People & Body", null),
    MechanicalLeg("🦿", "mechanical_leg", "People & Body", null),
    CheeseWedge("🧀", "cheese_wedge", "Food & Drink", 9),
    Cupcake("🧁", "cupcake", "Food & Drink", null),
    Salt("🧂", "salt", "Food & Drink", null),
    BeverageBox("🧃", "beverage_box", "Food & Drink", null),
    Garlic("🧄", "garlic", "Food & Drink", null),
    Onion("🧅", "onion", "Food & Drink", null),
    Falafel("🧆", "falafel", "Food & Drink", null),
    Waffle("🧇", "waffle", "Food & Drink", null),
    Butter("🧈", "butter", "Food & Drink", null),
    MateDrink("🧉", "mate_drink", "Food & Drink", null),
    IceCube("🧊", "ice_cube", "Food & Drink", null),
    WomanStanding("🧍‍♀️", "woman_standing", "People & Body", null),
    ManStanding("🧍‍♂️", "man_standing", "People & Body", null),
    StandingPerson("🧍", "standing_person", "People & Body", null),
    WomanKneeling("🧎‍♀️", "woman_kneeling", "People & Body", null),
    ManKneeling("🧎‍♂️", "man_kneeling", "People & Body", null),
    KneelingPerson("🧎", "kneeling_person", "People & Body", null),
    DeafWoman("🧏‍♀️", "deaf_woman", "People & Body", null),
    DeafMan("🧏‍♂️", "deaf_man", "People & Body", null),
    DeafPerson("🧏", "deaf_person", "People & Body", null),
    FaceWithMonocle("🧐", "face_with_monocle", "Smileys & Emotion", 7),
    Farmer("🧑‍🌾", "farmer", "People & Body", null),
    Cook("🧑‍🍳", "cook", "People & Body", null),
    Student("🧑‍🎓", "student", "People & Body", null),
    Singer("🧑‍🎤", "singer", "People & Body", null),
    Artist("🧑‍🎨", "artist", "People & Body", null),
    Teacher("🧑‍🏫", "teacher", "People & Body", null),
    FactoryWorker("🧑‍🏭", "factory_worker", "People & Body", null),
    Technologist("🧑‍💻", "technologist", "People & Body", null),
    OfficeWorker("🧑‍💼", "office_worker", "People & Body", null),
    Mechanic("🧑‍🔧", "mechanic", "People & Body", null),
    Scientist("🧑‍🔬", "scientist", "People & Body", null),
    Astronaut("🧑‍🚀", "astronaut", "People & Body", null),
    Firefighter("🧑‍🚒", "firefighter", "People & Body", null),
    PeopleHoldingHands("🧑‍🤝‍🧑", "people_holding_hands", "People & Body", null),
    PersonWithProbingCane("🧑‍🦯", "person_with_probing_cane", "People & Body", null),
    RedHairedPerson("🧑‍🦰", "red_haired_person", "People & Body", null),
    CurlyHairedPerson("🧑‍🦱", "curly_haired_person", "People & Body", null),
    BaldPerson("🧑‍🦲", "bald_person", "People & Body", null),
    WhiteHairedPerson("🧑‍🦳", "white_haired_person", "People & Body", null),
    PersonInMotorizedWheelchair("🧑‍🦼", "person_in_motorized_wheelchair", "People & Body", null),
    PersonInManualWheelchair("🧑‍🦽", "person_in_manual_wheelchair", "People & Body", null),
    HealthWorker("🧑‍⚕️", "health_worker", "People & Body", null),
    Judge("🧑‍⚖️", "judge", "People & Body", null),
    Pilot("🧑‍✈️", "pilot", "People & Body", null),
    Adult("🧑", "adult", "People & Body", 11),
    Child("🧒", "child", "People & Body", 11),
    OlderAdult("🧓", "older_adult", "People & Body", 12),
    BeardedPerson("🧔", "bearded_person", "People & Body", 10),
    PersonWithHeadscarf("🧕", "person_with_headscarf", "People & Body", 11),
    WomanInSteamyRoom("🧖‍♀️", "woman_in_steamy_room", "People & Body", null),
    ManInSteamyRoom("🧖‍♂️", "man_in_steamy_room", "People & Body", null),
    PersonInSteamyRoom("🧖", "person_in_steamy_room", "People & Body", 11),
    WomanClimbing("🧗‍♀️", "woman_climbing", "People & Body", null),
    ManClimbing("🧗‍♂️", "man_climbing", "People & Body", null),
    PersonClimbing("🧗", "person_climbing", "People & Body", 13),
    WomanInLotusPosition("🧘‍♀️", "woman_in_lotus_position", "People & Body", null),
    ManInLotusPosition("🧘‍♂️", "man_in_lotus_position", "People & Body", null),
    PersonInLotusPosition("🧘", "person_in_lotus_position", "People & Body", 9),
    FemaleMage("🧙‍♀️", "female_mage", "People & Body", null),
    MaleMage("🧙‍♂️", "male_mage", "People & Body", null),
    Mage("🧙", "mage", "People & Body", 11),
    FemaleFairy("🧚‍♀️", "female_fairy", "People & Body", null),
    MaleFairy("🧚‍♂️", "male_fairy", "People & Body", null),
    Fairy("🧚", "fairy", "People & Body", 8),
    FemaleVampire("🧛‍♀️", "female_vampire", "People & Body", null),
    MaleVampire("🧛‍♂️", "male_vampire", "People & Body", null),
    Vampire("🧛", "vampire", "People & Body", 12),
    Mermaid("🧜‍♀️", "mermaid", "People & Body", null),
    Merman("🧜‍♂️", "merman", "People & Body", null),
    Merperson("🧜", "merperson", "People & Body", 10),
    FemaleElf("🧝‍♀️", "female_elf", "People & Body", null),
    MaleElf("🧝‍♂️", "male_elf", "People & Body", null),
    Elf("🧝", "elf", "People & Body", 12),
    FemaleGenie("🧞‍♀️", "female_genie", "People & Body", null),
    MaleGenie("🧞‍♂️", "male_genie", "People & Body", null),
    Genie("🧞", "genie", "People & Body", 11),
    FemaleZombie("🧟‍♀️", "female_zombie", "People & Body", null),
    MaleZombie("🧟‍♂️", "male_zombie", "People & Body", null),
    Zombie("🧟", "zombie", "People & Body", 10),
    Brain("🧠", "brain", "People & Body", 10),
    OrangeHeart("🧡", "orange_heart", "Smileys & Emotion", 6),
    BilledCap("🧢", "billed_cap", "Objects", 9),
    Scarf("🧣", "scarf", "Objects", 13),
    Gloves("🧤", "gloves", "Objects", 12),
    Coat("🧥", "coat", "Objects", 13),
    Socks("🧦", "socks", "Objects", 12),
    RedEnvelope("🧧", "red_envelope", "Activities", null),
    Firecracker("🧨", "firecracker", "Activities", null),
    Jigsaw("🧩", "jigsaw", "Activities", null),
    TestTube("🧪", "test_tube", "Objects", null),
    PetriDish("🧫", "petri_dish", "Objects", null),
    Dna("🧬", "dna", "Objects", null),
    Compass("🧭", "compass", "Travel & Places", null),
    Abacus("🧮", "abacus", "Objects", null),
    FireExtinguisher("🧯", "fire_extinguisher", "Objects", null),
    Toolbox("🧰", "toolbox", "Objects", null),
    Bricks("🧱", "bricks", "Travel & Places", null),
    Magnet("🧲", "magnet", "Objects", null),
    Luggage("🧳", "luggage", "Travel & Places", null),
    LotionBottle("🧴", "lotion_bottle", "Objects", null),
    Thread("🧵", "thread", "Activities", null),
    Yarn("🧶", "yarn", "Activities", null),
    SafetyPin("🧷", "safety_pin", "Objects", null),
    TeddyBear("🧸", "teddy_bear", "Activities", null),
    Broom("🧹", "broom", "Objects", null),
    Basket("🧺", "basket", "Objects", null),
    RollOfPaper("🧻", "roll_of_paper", "Objects", null),
    Soap("🧼", "soap", "Objects", null),
    Sponge("🧽", "sponge", "Objects", null),
    Receipt("🧾", "receipt", "Objects", null),
    NazarAmulet("🧿", "nazar_amulet", "Activities", null),
    BalletShoes("🩰", "ballet_shoes", "Objects", null),
    OnePieceSwimsuit("🩱", "one-piece_swimsuit", "Objects", null),
    Briefs("🩲", "briefs", "Objects", null),
    Shorts("🩳", "shorts", "Objects", null),
    DropOfBlood("🩸", "drop_of_blood", "Objects", null),
    AdhesiveBandage("🩹", "adhesive_bandage", "Objects", null),
    Stethoscope("🩺", "stethoscope", "Objects", null),
    YoYo("🪀", "yo-yo", "Activities", null),
    Kite("🪁", "kite", "Activities", null),
    Parachute("🪂", "parachute", "Travel & Places", null),
    RingedPlanet("🪐", "ringed_planet", "Travel & Places", null),
    Chair("🪑", "chair", "Objects", null),
    Razor("🪒", "razor", "Objects", null),
    Axe("🪓", "axe", "Objects", null),
    DiyaLamp("🪔", "diya_lamp", "Objects", null),
    Banjo("🪕", "banjo", "Objects", null),
    Bangbang("‼️", "bangbang", "Symbols", 4),
    Interrobang("⁉️", "interrobang", "Symbols", 7),
    Tm("™️", "tm", "Symbols", null),
    InformationSource("ℹ️", "information_source", "Symbols", 12),
    LeftRightArrow("↔️", "left_right_arrow", "Symbols", 9),
    ArrowUpDown("↕️", "arrow_up_down", "Symbols", 11),
    ArrowUpperLeft("↖️", "arrow_upper_left", "Symbols", 12),
    ArrowUpperRight("↗️", "arrow_upper_right", "Symbols", 9),
    ArrowLowerRight("↘️", "arrow_lower_right", "Symbols", 9),
    ArrowLowerLeft("↙️", "arrow_lower_left", "Symbols", 11),
    LeftwardsArrowWithHook("↩️", "leftwards_arrow_with_hook", "Symbols", 12),
    ArrowRightHook("↪️", "arrow_right_hook", "Symbols", 11),
    Watch("⌚", "watch", "Travel & Places", 10),
    Hourglass("⌛", "hourglass", "Travel & Places", 11),
    Keyboard("⌨️", "keyboard", "Objects", 13),
    Eject("⏏️", "eject", "Symbols", 16),
    FastForward("⏩", "fast_forward", "Symbols", 9),
    Rewind("⏪", "rewind", "Symbols", 12),
    ArrowDoubleUp("⏫", "arrow_double_up", "Symbols", 12),
    ArrowDoubleDown("⏬", "arrow_double_down", "Symbols", 10),
    BlackRightPointingDoubleTriangleWithVerticalBar(
        "⏭️", "black_right_pointing_double_triangle_with_vertical_bar", "Symbols",
        13
    ),
    BlackLeftPointingDoubleTriangleWithVerticalBar(
        "⏮️",
        "black_left_pointing_double_triangle_with_vertical_bar",
        "Symbols",
        14
    ),
    BlackRightPointingTriangleWithDoubleVerticalBar(
        "⏯️", "black_right_pointing_triangle_with_double_vertical_bar", "Symbols",
        13
    ),
    AlarmClock("⏰", "alarm_clock", "Travel & Places", 8),
    Stopwatch("⏱️", "stopwatch", "Travel & Places", 10),
    TimerClock("⏲️", "timer_clock", "Travel & Places", 12),
    HourglassFlowingSand("⏳", "hourglass_flowing_sand", "Travel & Places", 10),
    DoubleVerticalBar("⏸️", "double_vertical_bar", "Symbols", 13),
    BlackSquareForStop("⏹️", "black_square_for_stop", "Symbols", 12),
    BlackCircleForRecord("⏺️", "black_circle_for_record", "Symbols", 12),
    M("Ⓜ️", "m", "Symbols", 11),
    BlackSmallSquare("▪️", "black_small_square", "Symbols", 8),
    WhiteSmallSquare("▫️", "white_small_square", "Symbols", 9),
    ArrowForward("▶️", "arrow_forward", "Symbols", 7),
    ArrowBackward("◀️", "arrow_backward", "Symbols", 9),
    WhiteMediumSquare("◻️", "white_medium_square", "Symbols", 12),
    BlackMediumSquare("◼️", "black_medium_square", "Symbols", 11),
    WhiteMediumSmallSquare("◽", "white_medium_small_square", "Symbols", 11),
    BlackMediumSmallSquare("◾", "black_medium_small_square", "Symbols", 11),
    Sunny("☀️", "sunny", "Travel & Places", 5),
    Cloud("☁️", "cloud", "Travel & Places", 8),
    Umbrella("☂️", "umbrella", "Travel & Places", 10),
    Snowman("☃️", "snowman", "Travel & Places", 10),
    Comet("☄️", "comet", "Travel & Places", 9),
    Phone("☎️", "phone", "Objects", 7),
    BallotBoxWithCheck("☑️", "ballot_box_with_check", "Symbols", 8),
    UmbrellaWithRainDrops("☔", "umbrella_with_rain_drops", "Travel & Places", 7),
    Coffee("☕", "coffee", "Food & Drink", 6),
    Shamrock("☘️", "shamrock", "Animals & Nature", 8),
    PointUp("☝️", "point_up", "People & Body", 6),
    SkullAndCrossbones("☠️", "skull_and_crossbones", "Smileys & Emotion", 8),
    RadioactiveSign("☢️", "radioactive_sign", "Symbols", 11),
    BiohazardSign("☣️", "biohazard_sign", "Symbols", 11),
    OrthodoxCross("☦️", "orthodox_cross", "Symbols", 13),
    StarAndCrescent("☪️", "star_and_crescent", "Symbols", 11),
    PeaceSymbol("☮️", "peace_symbol", "Symbols", 10),
    YinYang("☯️", "yin_yang", "Symbols", 10),
    WheelOfDharma("☸️", "wheel_of_dharma", "Symbols", 13),
    WhiteFrowningFace("☹️", "white_frowning_face", "Smileys & Emotion", 6),
    Relaxed("☺️", "relaxed", "Smileys & Emotion", 3),
    FemaleSign("♀️", "female_sign", "Symbols", null),
    MaleSign("♂️", "male_sign", "Symbols", null),
    Aries("♈", "aries", "Symbols", 11),
    Taurus("♉", "taurus", "Symbols", 12),
    Gemini("♊", "gemini", "Symbols", 11),
    Cancer("♋", "cancer", "Symbols", 11),
    Leo("♌", "leo", "Symbols", 12),
    Virgo("♍", "virgo", "Symbols", 12),
    Libra("♎", "libra", "Symbols", 12),
    Scorpius("♏", "scorpius", "Symbols", 12),
    Sagittarius("♐", "sagittarius", "Symbols", 12),
    Capricorn("♑", "capricorn", "Symbols", 12),
    Aquarius("♒", "aquarius", "Symbols", 12),
    Pisces("♓", "pisces", "Symbols", 12),
    ChessPawn("♟️", "chess_pawn", "Activities", null),
    Spades("♠️", "spades", "Activities", 9),
    Clubs("♣️", "clubs", "Activities", 9),
    Hearts("♥️", "hearts", "Activities", 3),
    Diamonds("♦️", "diamonds", "Activities", 9),
    Hotsprings("♨️", "hotsprings", "Travel & Places", 8),
    Recycle("♻️", "recycle", "Symbols", 9),
    Infinity("♾️", "infinity", "Symbols", null),
    Wheelchair("♿", "wheelchair", "Symbols", 11),
    HammerAndPick("⚒️", "hammer_and_pick", "Objects", 11),
    Anchor("⚓", "anchor", "Travel & Places", 10),
    CrossedSwords("⚔️", "crossed_swords", "Objects", 9),
    MedicalSymbol("⚕️", "medical_symbol", "Symbols", 12),
    Scales("⚖️", "scales", "Objects", 10),
    Alembic("⚗️", "alembic", "Objects", 14),
    Gear("⚙️", "gear", "Objects", 10),
    AtomSymbol("⚛️", "atom_symbol", "Symbols", 12),
    FleurDeLis("⚜️", "fleur_de_lis", "Symbols", 9),
    Warning("⚠️", "warning", "Symbols", 7),
    Zap("⚡", "zap", "Travel & Places", 6),
    WhiteCircle("⚪", "white_circle", "Symbols", 8),
    BlackCircle("⚫", "black_circle", "Symbols", 8),
    Coffin("⚰️", "coffin", "Objects", 10),
    FuneralUrn("⚱️", "funeral_urn", "Objects", 14),
    Soccer("⚽", "soccer", "Activities", 6),
    Baseball("⚾", "baseball", "Activities", 8),
    SnowmanWithoutSnow("⛄", "snowman_without_snow", "Travel & Places", 10),
    PartlySunny("⛅", "partly_sunny", "Travel & Places", 10),
    ThunderCloudAndRain("⛈️", "thunder_cloud_and_rain", "Travel & Places", 10),
    Ophiuchus("⛎", "ophiuchus", "Symbols", 15),
    Pick("⛏️", "pick", "Objects", 11),
    HelmetWithWhiteCross("⛑️", "helmet_with_white_cross", "Objects", 12),
    Chains("⛓️", "chains", "Objects", 11),
    NoEntry("⛔", "no_entry", "Symbols", 10),
    ShintoShrine("⛩️", "shinto_shrine", "Travel & Places", 10),
    Church("⛪", "church", "Travel & Places", 11),
    Mountain("⛰️", "mountain", "Travel & Places", 11),
    UmbrellaOnGround("⛱️", "umbrella_on_ground", "Travel & Places", 11),
    Fountain("⛲", "fountain", "Travel & Places", 12),
    Golf("⛳", "golf", "Activities", 10),
    Ferry("⛴️", "ferry", "Travel & Places", 12),
    Boat("⛵", "boat", "Travel & Places", 11),
    Skier("⛷️", "skier", "People & Body", 12),
    IceSkate("⛸️", "ice_skate", "Activities", 12),
    WomanBouncingBall("⛹️‍♀️", "woman-bouncing-ball", "People & Body", null),
    ManBouncingBall("⛹️‍♂️", "man-bouncing-ball", "People & Body", null),
    PersonWithBall("⛹️", "person_with_ball", "People & Body", 11),
    Tent("⛺", "tent", "Travel & Places", 12),
    Fuelpump("⛽", "fuelpump", "Travel & Places", 11),
    Scissors("✂️", "scissors", "Objects", 9),
    WhiteCheckMark("✅", "white_check_mark", "Symbols", 5),
    Airplane("✈️", "airplane", "Travel & Places", 7),
    Email("✉️", "email", "Objects", 10),
    Fist("✊", "fist", "People & Body", 6),
    Hand("✋", "hand", "People & Body", 5),
    V("✌️", "v", "People & Body", 4),
    WritingHand("✍️", "writing_hand", "People & Body", 7),
    Pencil2("✏️", "pencil2", "Objects", 9),
    BlackNib("✒️", "black_nib", "Objects", 10),
    HeavyCheckMark("✔️", "heavy_check_mark", "Symbols", 6),
    HeavyMultiplicationX("✖️", "heavy_multiplication_x", "Symbols", 9),
    LatinCross("✝️", "latin_cross", "Symbols", 9),
    StarOfDavid("✡️", "star_of_david", "Symbols", 11),
    Sparkles("✨", "sparkles", "Activities", 4),
    EightSpokedAsterisk("✳️", "eight_spoked_asterisk", "Symbols", 10),
    EightPointedBlackStar("✴️", "eight_pointed_black_star", "Symbols", 9),
    Snowflake("❄️", "snowflake", "Travel & Places", 7),
    Sparkle("❇️", "sparkle", "Symbols", 10),
    X("❌", "x", "Symbols", 6),
    NegativeSquaredCrossMark("❎", "negative_squared_cross_mark", "Symbols", 10),
    Question("❓", "question", "Symbols", 7),
    GreyQuestion("❔", "grey_question", "Symbols", 11),
    GreyExclamation("❕", "grey_exclamation", "Symbols", 9),
    Exclamation("❗", "exclamation", "Symbols", 5),
    HeavyHeartExclamationMarkOrnament("❣️", "heavy_heart_exclamation_mark_ornament", "Smileys & Emotion", 4),
    Heart("❤️", "heart", "Smileys & Emotion", 0),
    HeavyPlusSign("➕", "heavy_plus_sign", "Symbols", 10),
    HeavyMinusSign("➖", "heavy_minus_sign", "Symbols", 9),
    HeavyDivisionSign("➗", "heavy_division_sign", "Symbols", 13),
    ArrowRight("➡️", "arrow_right", "Symbols", 7),
    CurlyLoop("➰", "curly_loop", "Symbols", 10),
    Loop("➿", "loop", "Symbols", 12),
    ArrowHeadingUp("⤴️", "arrow_heading_up", "Symbols", 11),
    ArrowHeadingDown("⤵️", "arrow_heading_down", "Symbols", 7),
    ArrowLeft("⬅️", "arrow_left", "Symbols", 9),
    ArrowUp("⬆️", "arrow_up", "Symbols", 9),
    ArrowDown("⬇️", "arrow_down", "Symbols", 7),
    BlackLargeSquare("⬛", "black_large_square", "Symbols", 11),
    WhiteLargeSquare("⬜", "white_large_square", "Symbols", 12),
    Star("⭐", "star", "Travel & Places", 5),
    O("⭕", "o", "Symbols", 8),
    WavyDash("〰️", "wavy_dash", "Symbols", 9),
    PartAlternationMark("〽️", "part_alternation_mark", "Symbols", 11),
    Congratulations("㊗️", "congratulations", "Symbols", 9),
    Secret("㊙️", "secret", "Symbols", 11),
    ;

    @JsExport.Ignore
    fun category(): EmojiCategoryType {
        return EmojiCategoryType.of(category)
    }

    companion object {
        fun fromCategory(category: EmojiCategoryType): List<EmojiType> {
            return entries.toTypedArray()
                .filter { it.category == category.code }
        }
    }
}
